// City names use English common/international forms (e.g. Istanbul, Munich, Cologne).

export type CityEntry = { name: string };
export type UsStateEntry = { code: string; name: string };
export type CitiesByCountry = Record<string, CityEntry[]>;
export type UsCitiesByState = Record<string, CityEntry[]>;

export const US_STATES: UsStateEntry[] = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];

export const CITIES_BY_COUNTRY: CitiesByCountry = {
  "AD": [
  { name: "Andorra la Vella" },
  { name: "Encamp" },
  { name: "Escaldes-Engordany" },
],
  "AE": [
  { name: "Abu Dhabi" },
  { name: "Adh Dhayd" },
  { name: "Ajman City" },
  { name: "Al Ain City" },
  { name: "Al Fujairah City" },
  { name: "Al Shamkhah City" },
  { name: "Ar Ruways" },
  { name: "Bani Yas City" },
  { name: "Dibba Al-Fujairah" },
  { name: "Dibba Al-Hisn" },
  { name: "Dubai" },
  { name: "Khalifah A City" },
  { name: "Khawr Fakkan" },
  { name: "Musaffah" },
  { name: "Muzayri‘" },
  { name: "Ras Al Khaimah City" },
  { name: "Reef Al Fujairah City" },
  { name: "Sharjah" },
  { name: "Umm Al Quwain City" },
  { name: "Zayed City" },
],
  "AL": [
  { name: "Berat" },
  { name: "Bulqize" },
  { name: "Burrel" },
  { name: "Cerrik" },
  { name: "Corovode" },
  { name: "Durres" },
  { name: "Elbasan" },
  { name: "Fier" },
  { name: "Fier-Cifci" },
  { name: "Gjirokaster" },
  { name: "Gramsh" },
  { name: "Kavaje" },
  { name: "Korce" },
  { name: "Kruje" },
  { name: "Kucove" },
  { name: "Kukes" },
  { name: "Lac" },
  { name: "Lezhe" },
  { name: "Librazhd-Qender" },
  { name: "Lushnje" },
  { name: "Patos" },
  { name: "Patos Fshat" },
  { name: "Peshkopi" },
  { name: "Pogradec" },
  { name: "Sarande" },
  { name: "Shijak" },
  { name: "Shkoder" },
  { name: "Tepelene" },
  { name: "Tirana" },
  { name: "Vlore" },
],
  "AM": [
  { name: "Abovyan" },
  { name: "Akhuryan" },
  { name: "Alaverdi" },
  { name: "Ararat" },
  { name: "Armavir" },
  { name: "Artashat" },
  { name: "Ashtarak" },
  { name: "Berd" },
  { name: "Dilijan" },
  { name: "Gavarr" },
  { name: "Goris" },
  { name: "Gyumri" },
  { name: "Hats’avan" },
  { name: "Hrazdan" },
  { name: "Ijevan" },
  { name: "Kapan" },
  { name: "Martuni" },
  { name: "Masis" },
  { name: "Metsamor" },
  { name: "Sevan" },
  { name: "Spitak" },
  { name: "Step’anavan" },
  { name: "Vagharshapat" },
  { name: "Vanadzor" },
  { name: "Vardenik" },
  { name: "Vardenis" },
  { name: "Vedi" },
  { name: "Yeghegnadzor" },
  { name: "Yeghvard" },
  { name: "Yerevan" },
],
  "AT": [
  { name: "Amstetten" },
  { name: "Andritz" },
  { name: "Baden" },
  { name: "Bregenz" },
  { name: "Donaustadt" },
  { name: "Dornbirn" },
  { name: "Eggenberg" },
  { name: "Favoriten" },
  { name: "Feldkirch" },
  { name: "Floridsdorf" },
  { name: "Geidorf" },
  { name: "Graz" },
  { name: "Gries" },
  { name: "Hernals" },
  { name: "Hietzing" },
  { name: "Hohenems" },
  { name: "Hotting" },
  { name: "Innere Stadt" },
  { name: "Innsbruck" },
  { name: "Jakomini" },
  { name: "Klagenfurt am Worthersee" },
  { name: "Klosterneuburg" },
  { name: "Lend" },
  { name: "Linz" },
  { name: "Lustenau" },
  { name: "Meidling" },
  { name: "Modling" },
  { name: "Ottakring" },
  { name: "Pradl" },
  { name: "Salzburg" },
  { name: "Sankt Leonhard" },
  { name: "Sankt Martin" },
  { name: "Sankt Peter" },
  { name: "Sankt Polten" },
  { name: "Simmering" },
  { name: "Steyr" },
  { name: "Stockerau" },
  { name: "Strassgang" },
  { name: "Vienna" },
  { name: "Villach" },
  { name: "Weinzierl bei Krems" },
  { name: "Wels" },
  { name: "Wetzelsdorf" },
  { name: "Wiener Neustadt" },
  { name: "Wilten" },
],
  "AU": [
  { name: "Adelaide" },
  { name: "Adelaide Hills" },
  { name: "Albany" },
  { name: "Alice Springs" },
  { name: "Armidale" },
  { name: "Ashfield" },
  { name: "Auburn" },
  { name: "Baldivis" },
  { name: "Ballarat" },
  { name: "Bankstown" },
  { name: "Bathurst" },
  { name: "Baulkham Hills" },
  { name: "Bendigo" },
  { name: "Bentleigh East" },
  { name: "Berwick" },
  { name: "Blacktown" },
  { name: "Brisbane" },
  { name: "Brunswick" },
  { name: "Buderim" },
  { name: "Bunbury" },
  { name: "Bundaberg" },
  { name: "Bundoora" },
  { name: "Caboolture" },
  { name: "Cairns" },
  { name: "Campsie" },
  { name: "Canberra" },
  { name: "Canning Vale" },
  { name: "Carlingford" },
  { name: "Caroline Springs" },
  { name: "Castle Hill" },
  { name: "Chatswood" },
  { name: "Coburg" },
  { name: "Coffs Harbour" },
  { name: "Craigieburn" },
  { name: "Croydon" },
  { name: "Dandenong" },
  { name: "Darwin" },
  { name: "Doncaster East" },
  { name: "Dubbo" },
  { name: "Endeavour Hills" },
  { name: "Epping" },
  { name: "Ferntree Gully" },
  { name: "Frankston" },
  { name: "Frankston East" },
  { name: "Geelong" },
  { name: "Geraldton" },
  { name: "Gladstone" },
  { name: "Glen Iris" },
  { name: "Glen Waverley" },
  { name: "Gold Coast" },
  { name: "Greenacre" },
  { name: "Hampton Park" },
  { name: "Hervey Bay" },
  { name: "Hobart" },
  { name: "Hoppers Crossing" },
  { name: "Hurstville" },
  { name: "Kellyville" },
  { name: "Kew" },
  { name: "Keysborough" },
  { name: "Kwinana" },
  { name: "Launceston" },
  { name: "Liverpool" },
  { name: "Logan City" },
  { name: "Mackay" },
  { name: "Maitland" },
  { name: "Mandurah" },
  { name: "Maroubra" },
  { name: "Marrickville" },
  { name: "Melbourne" },
  { name: "Melbourne City Centre" },
  { name: "Merrylands" },
  { name: "Mildura" },
  { name: "Mill Park" },
  { name: "Mornington" },
  { name: "Mosman" },
  { name: "Mount Gambier" },
  { name: "Mount Waverley" },
  { name: "Narre Warren" },
  { name: "Narre Warren South" },
  { name: "Newcastle" },
  { name: "Noble Park" },
  { name: "Northcote" },
  { name: "Orange" },
  { name: "Pakenham" },
  { name: "Palmerston" },
  { name: "Parramatta" },
  { name: "Perth" },
  { name: "Point Cook" },
  { name: "Port Macquarie" },
  { name: "Preston" },
  { name: "Quakers Hill" },
  { name: "Randwick" },
  { name: "Reservoir" },
  { name: "Richmond" },
  { name: "Robina" },
  { name: "Rockhampton" },
  { name: "Rockingham" },
  { name: "Rowville" },
  { name: "Ryde" },
  { name: "Saint Albans" },
  { name: "Shepparton" },
  { name: "South Morang" },
  { name: "South Yarra" },
  { name: "Southport" },
  { name: "St Albans" },
  { name: "Strathfield" },
  { name: "Sunbury" },
  { name: "Surfers Paradise" },
  { name: "Sydney" },
  { name: "Sydney Central Business District" },
  { name: "Tamworth" },
  { name: "Tarneit" },
  { name: "Toowoomba" },
  { name: "Townsville" },
  { name: "Traralgon" },
  { name: "Upper Coomera" },
  { name: "Warrnambool" },
  { name: "Werribee" },
  { name: "Wollongong" },
],
  "AZ": [
  { name: "Agdam" },
  { name: "Agdas" },
  { name: "Agdzhabedy" },
  { name: "Amirdzhan" },
  { name: "Bakıxanov" },
  { name: "Baku" },
  { name: "Barda" },
  { name: "Bilajari" },
  { name: "Biny Selo" },
  { name: "Buzovna" },
  { name: "Divichibazar" },
  { name: "Fizuli" },
  { name: "Ganja" },
  { name: "Geoktschai" },
  { name: "Hacı Zeynalabdin" },
  { name: "Hacıqabul" },
  { name: "Hovsan" },
  { name: "Imishli" },
  { name: "Jalilabad" },
  { name: "Khirdalan" },
  { name: "Kyurdarmir" },
  { name: "Lankaran" },
  { name: "Lokbatan" },
  { name: "Mastaga" },
  { name: "Mingelchaur" },
  { name: "Nakhchivan" },
  { name: "Neftcala" },
  { name: "Qaracuxur" },
  { name: "Qazax" },
  { name: "Quba" },
  { name: "Saatlı" },
  { name: "Sabirabad" },
  { name: "Sabuncu" },
  { name: "Salyan" },
  { name: "Shamakhi" },
  { name: "Shamkhor" },
  { name: "Sheki" },
  { name: "Shushi" },
  { name: "Sirvan" },
  { name: "Sumqayıt" },
  { name: "Xacmaz" },
  { name: "Xankandi" },
  { name: "Yevlakh" },
  { name: "Zabrat" },
  { name: "Zaqatala" },
],
  "BA": [
  { name: "Banja Luka" },
  { name: "Bihac" },
  { name: "Bijeljina" },
  { name: "Bileca" },
  { name: "Bosanska Krupa" },
  { name: "Brcko" },
  { name: "Bugojno" },
  { name: "Cazin" },
  { name: "Doboj" },
  { name: "Foca" },
  { name: "Gorazde" },
  { name: "Gracanica" },
  { name: "Gradacac" },
  { name: "Gradiska" },
  { name: "Kakanj" },
  { name: "Konjic" },
  { name: "Livno" },
  { name: "Mostar" },
  { name: "Mrkonjic Grad" },
  { name: "Prijedor" },
  { name: "Sanski Most" },
  { name: "Sarajevo" },
  { name: "Travnik" },
  { name: "Trebinje" },
  { name: "Tuzla" },
  { name: "Velika Kladusa" },
  { name: "Visoko" },
  { name: "Zavidovici" },
  { name: "Zenica" },
  { name: "Zivinice" },
],
  "BE": [
  { name: "Aalst" },
  { name: "Antwerp" },
  { name: "Beringen" },
  { name: "Beveren" },
  { name: "Braine-l'Alleud" },
  { name: "Brasschaat" },
  { name: "Brugge" },
  { name: "Brussels" },
  { name: "Charleroi" },
  { name: "Chatelet" },
  { name: "Dendermonde" },
  { name: "Deurne" },
  { name: "Dilbeek" },
  { name: "Geel" },
  { name: "Genk" },
  { name: "Ghent" },
  { name: "Halle" },
  { name: "Hasselt" },
  { name: "Heist-op-den-Berg" },
  { name: "Herstal" },
  { name: "Hoboken" },
  { name: "Ieper" },
  { name: "Knokke-Heist" },
  { name: "Kortrijk" },
  { name: "La Louviere" },
  { name: "Leuven" },
  { name: "Liege" },
  { name: "Lokeren" },
  { name: "Maasmechelen" },
  { name: "Mechelen" },
  { name: "Mons" },
  { name: "Mouscron" },
  { name: "Namur" },
  { name: "Ninove" },
  { name: "Ostend" },
  { name: "Roeselare" },
  { name: "Schoten" },
  { name: "Seraing" },
  { name: "Sint-Niklaas" },
  { name: "Sint-Truiden" },
  { name: "Tournai" },
  { name: "Turnhout" },
  { name: "Verviers" },
  { name: "Vilvoorde" },
  { name: "Waregem" },
],
  "BG": [
  { name: "Asenovgrad" },
  { name: "Asparuhovo" },
  { name: "Aytos" },
  { name: "Blagoevgrad" },
  { name: "Botevgrad" },
  { name: "Burgas" },
  { name: "Dimitrovgrad" },
  { name: "Dobrich" },
  { name: "Dupnitsa" },
  { name: "Gabrovo" },
  { name: "Gorna Oryahovitsa" },
  { name: "Gotse Delchev" },
  { name: "Haskovo" },
  { name: "Kardzhali" },
  { name: "Kazanlak" },
  { name: "Kyustendil" },
  { name: "Lom" },
  { name: "Lovech" },
  { name: "Montana" },
  { name: "Nova Zagora" },
  { name: "Pazardzhik" },
  { name: "Pernik" },
  { name: "Petrich" },
  { name: "Pleven" },
  { name: "Plovdiv" },
  { name: "Razgrad" },
  { name: "Ruse" },
  { name: "Samokov" },
  { name: "Sandanski" },
  { name: "Sevlievo" },
  { name: "Shumen" },
  { name: "Silistra" },
  { name: "Sliven" },
  { name: "Smolyan" },
  { name: "Sofia" },
  { name: "Stara Zagora" },
  { name: "Svishtov" },
  { name: "Targovishte" },
  { name: "Troyan" },
  { name: "Varna" },
  { name: "Veliko Turnovo" },
  { name: "Velingrad" },
  { name: "Vidin" },
  { name: "Vratsa" },
  { name: "Yambol" },
],
  "BY": [
  { name: "Asipovichy" },
  { name: "Babruysk" },
  { name: "Baranovichi" },
  { name: "Barysaw" },
  { name: "Brest" },
  { name: "Byaroza" },
  { name: "Bykhaw" },
  { name: "Dobrush" },
  { name: "Dzyarzhynsk" },
  { name: "Hlybokaye" },
  { name: "Homyel'" },
  { name: "Horad Zhodzina" },
  { name: "Horki" },
  { name: "Hrodna" },
  { name: "Ivatsevichy" },
  { name: "Kalinkavichy" },
  { name: "Kalodzishchy" },
  { name: "Kobryn" },
  { name: "Krychaw" },
  { name: "Lida" },
  { name: "Luninyets" },
  { name: "Lyepyel’" },
  { name: "Mahilyow" },
  { name: "Maladzyechna" },
  { name: "Mar’’ina Horka" },
  { name: "Mazyr" },
  { name: "Minsk" },
  { name: "Navapolatsk" },
  { name: "Novogrudok" },
  { name: "Orsha" },
  { name: "Pastavy" },
  { name: "Pinsk" },
  { name: "Polatsk" },
  { name: "Pruzhany" },
  { name: "Rahachow" },
  { name: "Rechytsa" },
  { name: "Salihorsk" },
  { name: "Slonim" },
  { name: "Slutsk" },
  { name: "Smarhon’" },
  { name: "Svyetlahorsk" },
  { name: "Vilyeyka" },
  { name: "Vitebsk" },
  { name: "Volkovysk" },
  { name: "Zhlobin" },
],
  "CA": [
  { name: "Abbotsford" },
  { name: "Ajax" },
  { name: "Aurora" },
  { name: "Barrie" },
  { name: "Belleville" },
  { name: "Blainville" },
  { name: "Brampton" },
  { name: "Brantford" },
  { name: "Brossard" },
  { name: "Burlington" },
  { name: "Burnaby" },
  { name: "Calgary" },
  { name: "Cambridge" },
  { name: "Charlottetown" },
  { name: "Chateauguay" },
  { name: "Chatham" },
  { name: "Chilliwack" },
  { name: "Coquitlam" },
  { name: "Cornwall" },
  { name: "Dartmouth" },
  { name: "Delta" },
  { name: "Dollard-Des Ormeaux" },
  { name: "Drummondville" },
  { name: "East York" },
  { name: "Edmonton" },
  { name: "Etobicoke" },
  { name: "Fort McMurray" },
  { name: "Fredericton" },
  { name: "Gatineau" },
  { name: "Granby" },
  { name: "Grande Prairie" },
  { name: "Greater Sudbury" },
  { name: "Guelph" },
  { name: "Halifax" },
  { name: "Hamilton" },
  { name: "Jonquiere" },
  { name: "Kamloops" },
  { name: "Kanata" },
  { name: "Kelowna" },
  { name: "Kingston" },
  { name: "Kitchener" },
  { name: "La Haute-Saint-Charles" },
  { name: "Ladner" },
  { name: "Laval" },
  { name: "Lethbridge" },
  { name: "Levis" },
  { name: "London" },
  { name: "Longueuil" },
  { name: "Maple Ridge" },
  { name: "Markham" },
  { name: "Medicine Hat" },
  { name: "Milton" },
  { name: "Mississauga" },
  { name: "Moncton" },
  { name: "Montreal" },
  { name: "Nanaimo" },
  { name: "Nepean" },
  { name: "New Westminster" },
  { name: "Newmarket" },
  { name: "Niagara Falls" },
  { name: "Norfolk County" },
  { name: "North Bay" },
  { name: "North Vancouver" },
  { name: "North York" },
  { name: "Notre-Dame-de-Grace" },
  { name: "Oakville" },
  { name: "Okanagan" },
  { name: "Oshawa" },
  { name: "Ottawa" },
  { name: "Peterborough" },
  { name: "Pickering" },
  { name: "Port Coquitlam" },
  { name: "Prince George" },
  { name: "Quebec" },
  { name: "Quinte West" },
  { name: "Red Deer" },
  { name: "Regina" },
  { name: "Repentigny" },
  { name: "Richmond" },
  { name: "Richmond Hill" },
  { name: "Rimouski" },
  { name: "Saguenay" },
  { name: "Saint John" },
  { name: "Saint-Eustache" },
  { name: "Saint-Hyacinthe" },
  { name: "Saint-Jean-sur-Richelieu" },
  { name: "Saint-Jerome" },
  { name: "Saint-Laurent" },
  { name: "Saint-Leonard" },
  { name: "Sarnia" },
  { name: "Saskatoon" },
  { name: "Sault Ste. Marie" },
  { name: "Scarborough" },
  { name: "Sherbrooke" },
  { name: "Sherwood Park" },
  { name: "Sorel-Tracy" },
  { name: "St. Albert" },
  { name: "St. Catharines" },
  { name: "St. John's" },
  { name: "Surrey" },
  { name: "Sydney" },
  { name: "Terrebonne" },
  { name: "Thunder Bay" },
  { name: "Timmins" },
  { name: "Toronto" },
  { name: "Trois-Rivieres" },
  { name: "Vancouver" },
  { name: "Vaughan" },
  { name: "Vernon" },
  { name: "Victoria" },
  { name: "Waterloo" },
  { name: "Welland" },
  { name: "West End" },
  { name: "West Vancouver" },
  { name: "White Rock" },
  { name: "Willowdale" },
  { name: "Windsor" },
  { name: "Winnipeg" },
  { name: "Woodstock" },
],
  "CH": [
  { name: "Baar" },
  { name: "Basel" },
  { name: "Bern" },
  { name: "Biel/Bienne" },
  { name: "Chur" },
  { name: "Dietikon" },
  { name: "Dubendorf" },
  { name: "Emmen" },
  { name: "Frauenfeld" },
  { name: "Fribourg" },
  { name: "Geneva" },
  { name: "Koniz" },
  { name: "Kriens" },
  { name: "La Chaux-de-Fonds" },
  { name: "Lancy" },
  { name: "Lausanne" },
  { name: "Lugano" },
  { name: "Luzern" },
  { name: "Meyrin" },
  { name: "Montreux" },
  { name: "Neuchatel" },
  { name: "Rapperswil" },
  { name: "Riehen" },
  { name: "Sankt Gallen" },
  { name: "Schaffhausen" },
  { name: "Sitten" },
  { name: "Thun" },
  { name: "Uster" },
  { name: "Vernier" },
  { name: "Winterthur" },
  { name: "Yverdon-les-Bains" },
  { name: "Zug" },
  { name: "Zurich" },
  { name: "Zurich (Kreis 10)" },
  { name: "Zurich (Kreis 11)" },
  { name: "Zurich (Kreis 12)" },
  { name: "Zurich (Kreis 2)" },
  { name: "Zurich (Kreis 3)" },
  { name: "Zurich (Kreis 3) / Sihlfeld" },
  { name: "Zurich (Kreis 4) / Aussersihl" },
  { name: "Zurich (Kreis 6)" },
  { name: "Zurich (Kreis 6) / Unterstrass" },
  { name: "Zurich (Kreis 7)" },
  { name: "Zurich (Kreis 9)" },
  { name: "Zurich (Kreis 9) / Altstetten" },
],
  "CN": [
  { name: "Anshan" },
  { name: "Anyang" },
  { name: "Baoding" },
  { name: "Baotou" },
  { name: "Bayan Nur" },
  { name: "Beijing" },
  { name: "Bengbu" },
  { name: "Benxi" },
  { name: "Changchun" },
  { name: "Changsha" },
  { name: "Changshu City" },
  { name: "Changzhi" },
  { name: "Changzhou" },
  { name: "Chengdu" },
  { name: "Chongqing" },
  { name: "Dadonghai" },
  { name: "Dalian" },
  { name: "Dandong" },
  { name: "Datong" },
  { name: "Dongguan" },
  { name: "Foshan" },
  { name: "Fushun" },
  { name: "Fuxin" },
  { name: "Fuzhou" },
  { name: "Guangzhou" },
  { name: "Guankou" },
  { name: "Guilin" },
  { name: "Guiyang" },
  { name: "Haikou" },
  { name: "Handan" },
  { name: "Hangzhou" },
  { name: "Harbin" },
  { name: "Hefei" },
  { name: "Hegang" },
  { name: "Hengyang" },
  { name: "Hohhot" },
  { name: "Huai'an" },
  { name: "Huaibei" },
  { name: "Huainan" },
  { name: "Huangshi" },
  { name: "Jiamusi" },
  { name: "Jieyang" },
  { name: "Jilin" },
  { name: "Jinan" },
  { name: "Jinzhou" },
  { name: "Kaifeng" },
  { name: "Kunming" },
  { name: "Kunshan" },
  { name: "Langfang" },
  { name: "Lanzhou" },
  { name: "Liaoyang" },
  { name: "Lijiang" },
  { name: "Luancheng" },
  { name: "Luoyang" },
  { name: "Mudanjiang" },
  { name: "Nanchang" },
  { name: "Nanchong" },
  { name: "Nanjing" },
  { name: "Nanning" },
  { name: "Nantong" },
  { name: "Neijiang" },
  { name: "Ningbo" },
  { name: "Ordos" },
  { name: "Panshan" },
  { name: "Pingdingshan" },
  { name: "Puyang" },
  { name: "Puyang Chengguanzhen" },
  { name: "Qingdao" },
  { name: "Qinhuangdao" },
  { name: "Qiqihar" },
  { name: "Shanghai" },
  { name: "Shangyu" },
  { name: "Shantou" },
  { name: "Shaoguan" },
  { name: "Shenyang" },
  { name: "Shenzhen" },
  { name: "Shihezi" },
  { name: "Shijiazhuang" },
  { name: "Shiyan" },
  { name: "Shuangyashan" },
  { name: "Siping" },
  { name: "Suzhou" },
  { name: "Tai’an" },
  { name: "Taiyuan" },
  { name: "Taizhou" },
  { name: "Tangshan" },
  { name: "Tianjin" },
  { name: "Tianshui" },
  { name: "Tongshan" },
  { name: "Urumqi" },
  { name: "Wenzhou" },
  { name: "Wuhan" },
  { name: "Wuxi" },
  { name: "Xi’an" },
  { name: "Xiamen" },
  { name: "Xiangtan" },
  { name: "Xianyang" },
  { name: "Xingtai" },
  { name: "Xining" },
  { name: "Xinxiang" },
  { name: "Xinyang" },
  { name: "Xuchang" },
  { name: "Yancheng" },
  { name: "Yangzhou" },
  { name: "Yantai" },
  { name: "Yingkou" },
  { name: "Yueyang" },
  { name: "Yunfu" },
  { name: "Zhabei" },
  { name: "Zhangjiakou" },
  { name: "Zhangzhou" },
  { name: "Zhanjiang" },
  { name: "Zhengzhou" },
  { name: "Zhenjiang" },
  { name: "Zhongshan" },
  { name: "Zhu Cheng City" },
  { name: "Zhumadian" },
  { name: "Zhuzhou" },
  { name: "Zibo" },
  { name: "Zigong" },
],
  "CY": [
  { name: "Aradippou" },
  { name: "Dali" },
  { name: "Deryneia" },
  { name: "Dhromolaxia" },
  { name: "Famagusta" },
  { name: "Geri" },
  { name: "Geroskipou" },
  { name: "Kyrenia" },
  { name: "Lapithos" },
  { name: "Larnaca" },
  { name: "Lefka" },
  { name: "Limassol" },
  { name: "Livadia" },
  { name: "Morfou" },
  { name: "Nicosia" },
  { name: "Paphos" },
  { name: "Paralimni" },
  { name: "Pergamos" },
  { name: "Protaras" },
  { name: "Rizokarpaso" },
  { name: "Strovolos" },
  { name: "Tseri" },
  { name: "Xylofagou" },
  { name: "Ypsonas" },
],
  "CZ": [
  { name: "Brno" },
  { name: "Ceska Lipa" },
  { name: "Ceske Budejovice" },
  { name: "Cheb" },
  { name: "Chomutov" },
  { name: "Decin" },
  { name: "Frydek-Mistek" },
  { name: "Havirov" },
  { name: "Hradec Kralove" },
  { name: "Jablonec nad Nisou" },
  { name: "Jihlava" },
  { name: "Karlovy Vary" },
  { name: "Karvina" },
  { name: "Kladno" },
  { name: "Kolin" },
  { name: "Kromeriz" },
  { name: "Liben" },
  { name: "Liberec" },
  { name: "Litvinov" },
  { name: "Mlada Boleslav" },
  { name: "Modrany" },
  { name: "Most" },
  { name: "Novy Jicin" },
  { name: "Olomouc" },
  { name: "Opava" },
  { name: "Orlova" },
  { name: "Ostrava" },
  { name: "Pardubice" },
  { name: "Pilsen" },
  { name: "Pisek" },
  { name: "Prague" },
  { name: "Prerov" },
  { name: "Pribram" },
  { name: "Prostejov" },
  { name: "Sumperk" },
  { name: "Tabor" },
  { name: "Teplice" },
  { name: "Trebic" },
  { name: "Trinec" },
  { name: "Trutnov" },
  { name: "Usti nad Labem" },
  { name: "Valasske Mezirici" },
  { name: "Vsetin" },
  { name: "Zlin" },
  { name: "Znojmo" },
],
  "DE": [
  { name: "Aachen" },
  { name: "Altona" },
  { name: "Augsburg" },
  { name: "Bergedorf" },
  { name: "Bergisch Gladbach" },
  { name: "Berlin" },
  { name: "Bielefeld" },
  { name: "Bochum" },
  { name: "Bochum-Hordel" },
  { name: "Bonn" },
  { name: "Bottrop" },
  { name: "Braunschweig" },
  { name: "Bremen" },
  { name: "Bremerhaven" },
  { name: "Charlottenburg" },
  { name: "Chemnitz" },
  { name: "Cologne" },
  { name: "Cottbus" },
  { name: "Darmstadt" },
  { name: "Dortmund" },
  { name: "Dresden" },
  { name: "Duisburg" },
  { name: "Duren" },
  { name: "Dusseldorf" },
  { name: "Eimsbuttel" },
  { name: "Erfurt" },
  { name: "Erlangen" },
  { name: "Essen" },
  { name: "Esslingen" },
  { name: "Flensburg" },
  { name: "Frankfurt" },
  { name: "Freiburg" },
  { name: "Friedrichshain" },
  { name: "Furth" },
  { name: "Gelsenkirchen" },
  { name: "Gera" },
  { name: "Gesundbrunnen" },
  { name: "Gottingen" },
  { name: "Gutersloh" },
  { name: "Hagen" },
  { name: "Halle (Saale)" },
  { name: "Hamburg" },
  { name: "Hamburg-Mitte" },
  { name: "Hamburg-Nord" },
  { name: "Hamm" },
  { name: "Hanau am Main" },
  { name: "Hanover" },
  { name: "Harburg" },
  { name: "Heidelberg" },
  { name: "Heilbronn" },
  { name: "Herne" },
  { name: "Hildesheim" },
  { name: "Ingolstadt" },
  { name: "Iserlohn" },
  { name: "Jena" },
  { name: "Kaiserslautern" },
  { name: "Karlsruhe" },
  { name: "Kassel" },
  { name: "Kiel" },
  { name: "Koblenz" },
  { name: "Krefeld" },
  { name: "Kreuzberg" },
  { name: "Leipzig" },
  { name: "Leverkusen" },
  { name: "Lubeck" },
  { name: "Ludwigsburg" },
  { name: "Ludwigshafen am Rhein" },
  { name: "Lunen" },
  { name: "Magdeburg" },
  { name: "Mainz" },
  { name: "Mannheim" },
  { name: "Marienthal" },
  { name: "Marl" },
  { name: "Marzahn" },
  { name: "Minden" },
  { name: "Moers" },
  { name: "Monchengladbach" },
  { name: "Mulheim" },
  { name: "Munich" },
  { name: "Munster" },
  { name: "Neue Neustadt" },
  { name: "Neukolln" },
  { name: "Neuss" },
  { name: "Nippes" },
  { name: "Nuremberg" },
  { name: "Oberhausen" },
  { name: "Offenbach" },
  { name: "Oldenburg" },
  { name: "Osnabruck" },
  { name: "Paderborn" },
  { name: "Pforzheim" },
  { name: "Potsdam" },
  { name: "Prenzlauer Berg" },
  { name: "Ratingen" },
  { name: "Recklinghausen" },
  { name: "Regensburg" },
  { name: "Remscheid" },
  { name: "Reutlingen" },
  { name: "Rostock" },
  { name: "Saarbrucken" },
  { name: "Salzgitter" },
  { name: "Schoneberg" },
  { name: "Schwerin" },
  { name: "Siegen" },
  { name: "Solingen" },
  { name: "Stuttgart" },
  { name: "Trier" },
  { name: "Tubingen" },
  { name: "Ulm" },
  { name: "Velbert" },
  { name: "Villingen-Schwenningen" },
  { name: "Wandsbek" },
  { name: "Wiesbaden" },
  { name: "Wilhelmshaven" },
  { name: "Wilmersdorf" },
  { name: "Witten" },
  { name: "Wolfsburg" },
  { name: "Wuppertal" },
  { name: "Wurzburg" },
  { name: "Zwickau" },
],
  "DK": [
  { name: "Aalborg" },
  { name: "Albertslund" },
  { name: "Arhus" },
  { name: "Ballerup" },
  { name: "Birkerod" },
  { name: "Charlottenlund" },
  { name: "Copenhagen" },
  { name: "Esbjerg" },
  { name: "Farum" },
  { name: "Fredericia" },
  { name: "Frederiksberg" },
  { name: "Frederikshavn" },
  { name: "Glostrup" },
  { name: "Greve" },
  { name: "Haderslev" },
  { name: "Helsingor" },
  { name: "Herning" },
  { name: "Hillerod" },
  { name: "Hjorring" },
  { name: "Holbaek" },
  { name: "Holstebro" },
  { name: "Horsens" },
  { name: "Horsholm" },
  { name: "Hvidovre" },
  { name: "Ishoj" },
  { name: "Koge" },
  { name: "Kolding" },
  { name: "Naestved" },
  { name: "Norresundby" },
  { name: "Nykobing Falster" },
  { name: "Odense" },
  { name: "Randers" },
  { name: "Ringsted" },
  { name: "Rodovre" },
  { name: "Roskilde" },
  { name: "Silkeborg" },
  { name: "Skive" },
  { name: "Slagelse" },
  { name: "Sonderborg" },
  { name: "Stenlose" },
  { name: "Svendborg" },
  { name: "Taastrup" },
  { name: "Vanlose" },
  { name: "Vejle" },
  { name: "Viborg" },
],
  "EE": [
  { name: "Elva" },
  { name: "Haapsalu" },
  { name: "Jogeva" },
  { name: "Johvi" },
  { name: "Keila" },
  { name: "Kivioli" },
  { name: "Kohtla-Jarve" },
  { name: "Kuressaare" },
  { name: "Maardu" },
  { name: "Narva" },
  { name: "Paide" },
  { name: "Parnu" },
  { name: "Polva" },
  { name: "Rakvere" },
  { name: "Rapla" },
  { name: "Saue" },
  { name: "Sillamae" },
  { name: "Tallinn" },
  { name: "Tapa" },
  { name: "Tartu" },
  { name: "Turi" },
  { name: "Valga" },
  { name: "Viljandi" },
  { name: "Voru" },
],
  "ES": [
  { name: "A Coruna" },
  { name: "Albacete" },
  { name: "Alcala de Henares" },
  { name: "Alcobendas" },
  { name: "Alcorcon" },
  { name: "Algeciras" },
  { name: "Algorta" },
  { name: "Alicante" },
  { name: "Almeria" },
  { name: "Arganzuela" },
  { name: "Arona" },
  { name: "Aviles" },
  { name: "Badajoz" },
  { name: "Badalona" },
  { name: "Barakaldo" },
  { name: "Barcelona" },
  { name: "Bilbao" },
  { name: "Burgos" },
  { name: "Caceres" },
  { name: "Cadiz" },
  { name: "Carabanchel" },
  { name: "Cartagena" },
  { name: "Castello de la Plana" },
  { name: "Ceuta" },
  { name: "Chamartin" },
  { name: "Chamberi" },
  { name: "City Center" },
  { name: "Ciudad Lineal" },
  { name: "Ciutat Vella" },
  { name: "Cordoba" },
  { name: "Cornella de Llobregat" },
  { name: "Coslada" },
  { name: "Delicias" },
  { name: "Donostia / San Sebastian" },
  { name: "Dos Hermanas" },
  { name: "Eixample" },
  { name: "El Ejido" },
  { name: "El Puerto de Santa Maria" },
  { name: "Elche" },
  { name: "Fuencarral-El Pardo" },
  { name: "Fuenlabrada" },
  { name: "Gandia" },
  { name: "Gasteiz / Vitoria" },
  { name: "Getafe" },
  { name: "Getxo" },
  { name: "Gijon" },
  { name: "Girona" },
  { name: "Gracia" },
  { name: "Granada" },
  { name: "Guadalajara" },
  { name: "Horta-Guinardo" },
  { name: "Hortaleza" },
  { name: "Huelva" },
  { name: "Jaen" },
  { name: "Jerez de la Frontera" },
  { name: "L'Hospitalet de Llobregat" },
  { name: "La Laguna" },
  { name: "Las Palmas de Gran Canaria" },
  { name: "Las Rozas de Madrid" },
  { name: "Latina" },
  { name: "Leganes" },
  { name: "Leon" },
  { name: "Les Corts" },
  { name: "Lleida" },
  { name: "Logrono" },
  { name: "Lorca" },
  { name: "Lugo" },
  { name: "Madrid" },
  { name: "Malaga" },
  { name: "Marbella" },
  { name: "Mataro" },
  { name: "Moncloa-Aravaca" },
  { name: "Moratalaz" },
  { name: "Mostoles" },
  { name: "Murcia" },
  { name: "Nou Barris" },
  { name: "Orihuela" },
  { name: "Ourense" },
  { name: "Oviedo" },
  { name: "Palencia" },
  { name: "Palma" },
  { name: "Pamplona" },
  { name: "Parla" },
  { name: "Pontevedra" },
  { name: "Pozuelo de Alarcon" },
  { name: "Puente de Vallecas" },
  { name: "Retiro" },
  { name: "Reus" },
  { name: "Roquetas de Mar" },
  { name: "Sabadell" },
  { name: "Salamanca" },
  { name: "San Blas-Canillejas" },
  { name: "San Fernando" },
  { name: "Sant Andreu" },
  { name: "Sant Boi de Llobregat" },
  { name: "Sant Cugat del Valles" },
  { name: "Sant Marti" },
  { name: "Santa Coloma de Gramenet" },
  { name: "Santa Cruz de Tenerife" },
  { name: "Santander" },
  { name: "Santiago de Compostela" },
  { name: "Sants-Montjuic" },
  { name: "Sarria-Sant Gervasi" },
  { name: "Sevilla" },
  { name: "Talavera de la Reina" },
  { name: "Tarragona" },
  { name: "Telde" },
  { name: "Terrassa" },
  { name: "Tetuan de las Victorias" },
  { name: "Toledo" },
  { name: "Torrejon de Ardoz" },
  { name: "Torrent" },
  { name: "Torrevieja" },
  { name: "Usera" },
  { name: "Valencia" },
  { name: "Valladolid" },
  { name: "Vigo" },
  { name: "Villaverde" },
  { name: "Zaragoza" },
],
  "FI": [
  { name: "Espoo" },
  { name: "Hameenlinna" },
  { name: "Helsinki" },
  { name: "Hyvinge" },
  { name: "Iisalmi" },
  { name: "Imatra" },
  { name: "Jarvenpaa" },
  { name: "Joensuu" },
  { name: "Jyvaskyla" },
  { name: "Kaarela" },
  { name: "Kajaani" },
  { name: "Kallio" },
  { name: "Kangasala" },
  { name: "Karhula" },
  { name: "Kemi" },
  { name: "Kerava" },
  { name: "Kirkkonummi" },
  { name: "Kokkola" },
  { name: "Kotka" },
  { name: "Kouvola" },
  { name: "Kuopio" },
  { name: "Lahti" },
  { name: "Lappeenranta" },
  { name: "Lohja" },
  { name: "Mellunkyla" },
  { name: "Mikkeli" },
  { name: "Nokia" },
  { name: "Nurmijarvi" },
  { name: "Oulu" },
  { name: "Pori" },
  { name: "Porvoo" },
  { name: "Raisio" },
  { name: "Rauma" },
  { name: "Riihimaki" },
  { name: "Rovaniemi" },
  { name: "Salo" },
  { name: "Savonlinna" },
  { name: "Seinajoki" },
  { name: "Tampere" },
  { name: "Turku" },
  { name: "Tuusula" },
  { name: "Vaasa" },
  { name: "Vantaa" },
  { name: "Vihti" },
  { name: "Vuosaari" },
],
  "FR": [
  { name: "Aix-en-Provence" },
  { name: "Ajaccio" },
  { name: "Albi" },
  { name: "Amiens" },
  { name: "Angers" },
  { name: "Antibes" },
  { name: "Antony" },
  { name: "Argenteuil" },
  { name: "Arles" },
  { name: "Asnieres-sur-Seine" },
  { name: "Aubervilliers" },
  { name: "Aulnay-sous-Bois" },
  { name: "Avignon" },
  { name: "Beauvais" },
  { name: "Belfort" },
  { name: "Besancon" },
  { name: "Beziers" },
  { name: "Blois" },
  { name: "Bordeaux" },
  { name: "Boulogne-Billancourt" },
  { name: "Bourges" },
  { name: "Brest" },
  { name: "Brive-la-Gaillarde" },
  { name: "Caen" },
  { name: "Calais" },
  { name: "Cannes" },
  { name: "Cergy" },
  { name: "Cergy-Pontoise" },
  { name: "Chambery" },
  { name: "Champigny-sur-Marne" },
  { name: "Charleville-Mezieres" },
  { name: "Chateauroux" },
  { name: "Cholet" },
  { name: "Clamart" },
  { name: "Clermont-Ferrand" },
  { name: "Clichy" },
  { name: "Colmar" },
  { name: "Colombes" },
  { name: "Courbevoie" },
  { name: "Creteil" },
  { name: "Dijon" },
  { name: "Drancy" },
  { name: "Dunkerque" },
  { name: "Evreux" },
  { name: "Evry" },
  { name: "Fontenay-sous-Bois" },
  { name: "Frejus" },
  { name: "Grenoble" },
  { name: "Issy-les-Moulineaux" },
  { name: "Ivry-sur-Seine" },
  { name: "La Roche-sur-Yon" },
  { name: "La Rochelle" },
  { name: "La Seyne-sur-Mer" },
  { name: "Le Havre" },
  { name: "Le Mans" },
  { name: "Levallois-Perret" },
  { name: "Lille" },
  { name: "Limoges" },
  { name: "Lorient" },
  { name: "Lyon" },
  { name: "Maisons-Alfort" },
  { name: "Marseille" },
  { name: "Marseille 08" },
  { name: "Marseille 09" },
  { name: "Marseille 11" },
  { name: "Marseille 12" },
  { name: "Marseille 13" },
  { name: "Marseille 14" },
  { name: "Marseille 15" },
  { name: "Meaux" },
  { name: "Merignac" },
  { name: "Metz" },
  { name: "Montauban" },
  { name: "Montpellier" },
  { name: "Montreuil" },
  { name: "Mulhouse" },
  { name: "Nancy" },
  { name: "Nanterre" },
  { name: "Nantes" },
  { name: "Neuilly-sur-Seine" },
  { name: "Nice" },
  { name: "Nimes" },
  { name: "Niort" },
  { name: "Noisy-le-Grand" },
  { name: "Orleans" },
  { name: "Pantin" },
  { name: "Paris" },
  { name: "Pau" },
  { name: "Perpignan" },
  { name: "Pessac" },
  { name: "Poitiers" },
  { name: "Quimper" },
  { name: "Reims" },
  { name: "Rennes" },
  { name: "Roubaix" },
  { name: "Rouen" },
  { name: "Rueil-Malmaison" },
  { name: "Saint-Brieuc" },
  { name: "Saint-Denis" },
  { name: "Saint-Etienne" },
  { name: "Saint-Maur-des-Fosses" },
  { name: "Saint-Nazaire" },
  { name: "Saint-Quentin" },
  { name: "Saint-Quentin-en-Yvelines" },
  { name: "Sarcelles" },
  { name: "Sartrouville" },
  { name: "Strasbourg" },
  { name: "Tarbes" },
  { name: "Toulon" },
  { name: "Toulouse" },
  { name: "Tourcoing" },
  { name: "Tours" },
  { name: "Troyes" },
  { name: "Valence" },
  { name: "Vannes" },
  { name: "Venissieux" },
  { name: "Versailles" },
  { name: "Villeneuve-d'Ascq" },
  { name: "Villeurbanne" },
  { name: "Vitry-sur-Seine" },
],
  "GB": [
  { name: "Aberdeen" },
  { name: "Archway" },
  { name: "Basildon" },
  { name: "Basingstoke" },
  { name: "Bath" },
  { name: "Becontree" },
  { name: "Bedford" },
  { name: "Belfast" },
  { name: "Bexley" },
  { name: "Birkenhead" },
  { name: "Birmingham" },
  { name: "Blackburn" },
  { name: "Blackpool" },
  { name: "Bolton" },
  { name: "Bournemouth" },
  { name: "Bradford" },
  { name: "Brent" },
  { name: "Brighton" },
  { name: "Bristol" },
  { name: "Burnley" },
  { name: "Burton upon Trent" },
  { name: "Cambridge" },
  { name: "Cannock" },
  { name: "Cardiff" },
  { name: "Chelmsford" },
  { name: "Cheltenham" },
  { name: "Chester" },
  { name: "Chesterfield" },
  { name: "City of Westminster" },
  { name: "Colchester" },
  { name: "Coventry" },
  { name: "Crawley" },
  { name: "Croydon" },
  { name: "Dagenham" },
  { name: "Darlington" },
  { name: "Derby" },
  { name: "Doncaster" },
  { name: "Dudley" },
  { name: "Dundee" },
  { name: "Eastbourne" },
  { name: "Edinburgh" },
  { name: "Enfield Town" },
  { name: "Exeter" },
  { name: "Gillingham" },
  { name: "Glasgow" },
  { name: "Gloucester" },
  { name: "Grays" },
  { name: "Grimsby" },
  { name: "Harlow" },
  { name: "Harrogate" },
  { name: "Hartlepool" },
  { name: "Hastings" },
  { name: "Hemel Hempstead" },
  { name: "High Peak" },
  { name: "High Wycombe" },
  { name: "Huddersfield" },
  { name: "Ipswich" },
  { name: "Islington" },
  { name: "Kingston upon Hull" },
  { name: "Leeds" },
  { name: "Leicester" },
  { name: "Lincoln" },
  { name: "Liverpool" },
  { name: "London" },
  { name: "Londonderry County Borough" },
  { name: "Luton" },
  { name: "Maidstone" },
  { name: "Manchester" },
  { name: "Mansfield" },
  { name: "Mendip" },
  { name: "Middlesbrough" },
  { name: "Milton Keynes" },
  { name: "Newcastle upon Tyne" },
  { name: "Newport" },
  { name: "Northampton" },
  { name: "Norwich" },
  { name: "Nottingham" },
  { name: "Nuneaton" },
  { name: "Oldham" },
  { name: "Oxford" },
  { name: "Peterborough" },
  { name: "Plymouth" },
  { name: "Poole" },
  { name: "Portsmouth" },
  { name: "Preston" },
  { name: "Reading" },
  { name: "Redditch" },
  { name: "Rochdale" },
  { name: "Romford" },
  { name: "Rotherham" },
  { name: "Royal Leamington Spa" },
  { name: "Saint Peters" },
  { name: "Sheffield" },
  { name: "Slough" },
  { name: "Solihull" },
  { name: "Southampton" },
  { name: "Southend-on-Sea" },
  { name: "Southport" },
  { name: "St Albans" },
  { name: "St Helens" },
  { name: "Stevenage" },
  { name: "Stockport" },
  { name: "Stoke-on-Trent" },
  { name: "Sunderland" },
  { name: "Sutton" },
  { name: "Sutton Coldfield" },
  { name: "Swansea" },
  { name: "Swindon" },
  { name: "Telford" },
  { name: "Walsall" },
  { name: "Warrington" },
  { name: "Watford" },
  { name: "Wembley" },
  { name: "West Bromwich" },
  { name: "Wigan" },
  { name: "Woking" },
  { name: "Wolverhampton" },
  { name: "Worcester" },
  { name: "Worthing" },
  { name: "York" },
],
  "GE": [
  { name: "Akhaltsikhe" },
  { name: "Batumi" },
  { name: "Bolnisi" },
  { name: "Borjomi" },
  { name: "Chiat’ura" },
  { name: "Gali" },
  { name: "Gardabani" },
  { name: "Gori" },
  { name: "K’asp’i" },
  { name: "Khashuri" },
  { name: "Kobuleti" },
  { name: "Kutaisi" },
  { name: "Marneuli" },
  { name: "Och’amch’ire" },
  { name: "Ozurgeti" },
  { name: "P’ot’i" },
  { name: "Rustavi" },
  { name: "Sagarejo" },
  { name: "Samtredia" },
  { name: "Senak’i" },
  { name: "Sokhumi" },
  { name: "Stantsiya Novyy Afon" },
  { name: "T’q’ibuli" },
  { name: "Tbilisi" },
  { name: "Telavi" },
  { name: "Tqvarch'eli" },
  { name: "Ts’khinvali" },
  { name: "Ts’q’alt’ubo" },
  { name: "Zest’aponi" },
  { name: "Zugdidi" },
],
  "GR": [
  { name: "Acharnes" },
  { name: "Agia Paraskevi" },
  { name: "Agios Dimitrios" },
  { name: "Agrinio" },
  { name: "Aigaleo" },
  { name: "Alexandroupoli" },
  { name: "Athens" },
  { name: "Chaidari" },
  { name: "Chalkida" },
  { name: "Chania" },
  { name: "Galatsi" },
  { name: "Glyfada" },
  { name: "Ilion" },
  { name: "Ilioupoli" },
  { name: "Ioannina" },
  { name: "Irakleio" },
  { name: "Irakleion" },
  { name: "Kalamaria" },
  { name: "Kalamata" },
  { name: "Kallithea" },
  { name: "Katerini" },
  { name: "Kavala" },
  { name: "Keratsini" },
  { name: "Khalandrion" },
  { name: "Kifisia" },
  { name: "Korydallos" },
  { name: "Lamia" },
  { name: "Larisa" },
  { name: "Marousi" },
  { name: "Nea Ionia" },
  { name: "Nea Smyrni" },
  { name: "Nikaia" },
  { name: "Palaio Faliro" },
  { name: "Patra" },
  { name: "Peristeri" },
  { name: "Petroupolis" },
  { name: "Piraeus" },
  { name: "Rodos" },
  { name: "Serres" },
  { name: "Thessaloniki" },
  { name: "Trikala" },
  { name: "Volos" },
  { name: "Vyronas" },
  { name: "Xanthi" },
  { name: "Zografos" },
],
  "HR": [
  { name: "Bjelovar" },
  { name: "Brezovica" },
  { name: "Cakovec" },
  { name: "Centar" },
  { name: "Dakovo" },
  { name: "Dubrovnik" },
  { name: "Karlovac" },
  { name: "Knin" },
  { name: "Koprivnica" },
  { name: "Krizevci" },
  { name: "Kutina" },
  { name: "Makarska" },
  { name: "Metkovic" },
  { name: "Nova Gradiska" },
  { name: "Osijek" },
  { name: "Petrinja" },
  { name: "Popovaca" },
  { name: "Porec" },
  { name: "Pozega" },
  { name: "Pula" },
  { name: "Rijeka" },
  { name: "Rovinj" },
  { name: "Samobor" },
  { name: "Sesvete" },
  { name: "Sibenik" },
  { name: "Sinj" },
  { name: "Sisak" },
  { name: "Slatina" },
  { name: "Slavonski Brod" },
  { name: "Solin" },
  { name: "Split" },
  { name: "Stenjevec" },
  { name: "Trogir" },
  { name: "Varazdin" },
  { name: "Velika Gorica" },
  { name: "Vinkovci" },
  { name: "Virovitica" },
  { name: "Vukovar" },
  { name: "Zadar" },
  { name: "Zagreb" },
  { name: "Zapresic" },
  { name: "Zupanja" },
],
  "HU": [
  { name: "Bekescsaba" },
  { name: "Budapest" },
  { name: "Budapest II. kerulet" },
  { name: "Budapest III. kerulet" },
  { name: "Budapest IV. kerulet" },
  { name: "Budapest VI. kerulet" },
  { name: "Budapest VIII. kerulet" },
  { name: "Budapest XI. kerulet" },
  { name: "Budapest XII. kerulet" },
  { name: "Budapest XIII. kerulet" },
  { name: "Budapest XIX. kerulet" },
  { name: "Budapest XV. kerulet" },
  { name: "Budapest XVI. kerulet" },
  { name: "Budapest XVII. kerulet" },
  { name: "Budapest XVIII. kerulet" },
  { name: "Budapest XX. kerulet" },
  { name: "Budapest XXI. kerulet" },
  { name: "Budapest XXII. kerulet" },
  { name: "Debrecen" },
  { name: "Dunaujvaros" },
  { name: "Eger" },
  { name: "Erd" },
  { name: "Erzsebetvaros" },
  { name: "Gyor" },
  { name: "Hodmezovasarhely" },
  { name: "Jozsefvaros" },
  { name: "Kaposvar" },
  { name: "Kecskemet" },
  { name: "Kispest" },
  { name: "Kobanya" },
  { name: "Miskolc" },
  { name: "Nagykanizsa" },
  { name: "Nyiregyhaza" },
  { name: "Paradsasvar" },
  { name: "Pecs" },
  { name: "Salgotarjan" },
  { name: "Sopron" },
  { name: "Szeged" },
  { name: "Szekesfehervar" },
  { name: "Szolnok" },
  { name: "Szombathely" },
  { name: "Tatabanya" },
  { name: "Veszprem" },
  { name: "Zalaegerszeg" },
  { name: "Zuglo" },
],
  "IE": [
  { name: "An Muileann gCearr" },
  { name: "Athlone" },
  { name: "Athy" },
  { name: "Balbriggan" },
  { name: "Blanchardstown" },
  { name: "Bray" },
  { name: "Carlow" },
  { name: "Carrigaline" },
  { name: "Castlebar" },
  { name: "Celbridge" },
  { name: "Clondalkin" },
  { name: "Cluain Meala" },
  { name: "Cork" },
  { name: "Donaghmede" },
  { name: "Drogheda" },
  { name: "Droichead Nua" },
  { name: "Dublin" },
  { name: "Dun Laoghaire" },
  { name: "Dundalk" },
  { name: "Dundrum" },
  { name: "Ennis" },
  { name: "Finglas" },
  { name: "Foxrock" },
  { name: "Gaillimh" },
  { name: "Greystones" },
  { name: "Kilkenny" },
  { name: "Kilquade" },
  { name: "Knocklyon" },
  { name: "Leixlip" },
  { name: "Letterkenny" },
  { name: "Loch Garman" },
  { name: "Lucan" },
  { name: "Luimneach" },
  { name: "Malahide" },
  { name: "Maynooth" },
  { name: "Naas" },
  { name: "Navan" },
  { name: "Portlaoise" },
  { name: "Sandyford" },
  { name: "Sligo" },
  { name: "Swords" },
  { name: "Tallaght" },
  { name: "Tralee" },
  { name: "Waterford" },
  { name: "Wicklow" },
],
  "IN": [
  { name: "Agra" },
  { name: "Ahmadnagar" },
  { name: "Ahmedabad" },
  { name: "Ajmer" },
  { name: "Akola" },
  { name: "Aligarh" },
  { name: "Allahabad" },
  { name: "Amravati" },
  { name: "Amritsar" },
  { name: "Asansol" },
  { name: "Aurangabad" },
  { name: "Bareilly" },
  { name: "Belgaum" },
  { name: "Bengaluru" },
  { name: "Bhatpara" },
  { name: "Bhavnagar" },
  { name: "Bhayandar" },
  { name: "Bhilai" },
  { name: "Bhiwandi" },
  { name: "Bhopal" },
  { name: "Bhubaneshwar" },
  { name: "Bikaner" },
  { name: "Bilimora" },
  { name: "Bokaro" },
  { name: "Borivli" },
  { name: "Chandigarh" },
  { name: "Chennai" },
  { name: "Cochin" },
  { name: "Coimbatore" },
  { name: "Cuttack" },
  { name: "Davangere" },
  { name: "Dehra Dun" },
  { name: "Delhi" },
  { name: "Dhulia" },
  { name: "Dombivli" },
  { name: "Durgapur" },
  { name: "Faridabad" },
  { name: "Gaya" },
  { name: "Ghaziabad" },
  { name: "Gorakhpur" },
  { name: "Gulbarga" },
  { name: "Guntur" },
  { name: "Guwahati" },
  { name: "Gwalior" },
  { name: "Haora" },
  { name: "Hubli" },
  { name: "Hyderabad" },
  { name: "Indore" },
  { name: "Jabalpur" },
  { name: "Jaipur" },
  { name: "Jalandhar" },
  { name: "Jalgaon" },
  { name: "Jammu" },
  { name: "Jamnagar" },
  { name: "Jamshedpur" },
  { name: "Jhansi" },
  { name: "Jodhpur" },
  { name: "Kalyan" },
  { name: "Kanpur" },
  { name: "Karol Bagh" },
  { name: "Kolhapur" },
  { name: "Kolkata" },
  { name: "Kollam" },
  { name: "Korba" },
  { name: "Kota" },
  { name: "Kozhikode" },
  { name: "Kurnool" },
  { name: "Lucknow" },
  { name: "Ludhiana" },
  { name: "Madurai" },
  { name: "Malegaon" },
  { name: "Mangalore" },
  { name: "Meerut" },
  { name: "Moradabad" },
  { name: "Mumbai" },
  { name: "Mysore" },
  { name: "Nagpur" },
  { name: "Najafgarh" },
  { name: "Nanded" },
  { name: "Nangi" },
  { name: "Narela" },
  { name: "Nashik" },
  { name: "Navi Mumbai" },
  { name: "Nellore" },
  { name: "Nowrangapur" },
  { name: "Panihati" },
  { name: "Patna" },
  { name: "Pimpri" },
  { name: "Pune" },
  { name: "Raipur" },
  { name: "Rajkot" },
  { name: "Ramgundam" },
  { name: "Ranchi" },
  { name: "Raurkela" },
  { name: "Rohini" },
  { name: "Saharanpur" },
  { name: "Salem" },
  { name: "Sangli" },
  { name: "Shivaji Nagar" },
  { name: "Shyamnagar" },
  { name: "Siliguri" },
  { name: "Solapur" },
  { name: "Srinagar" },
  { name: "Surat" },
  { name: "Teni" },
  { name: "Thane" },
  { name: "Thiruvananthapuram" },
  { name: "Thoothukudi" },
  { name: "Tiruchirappalli" },
  { name: "Tirunelveli" },
  { name: "Tiruppur" },
  { name: "Udaipur" },
  { name: "Ujjain" },
  { name: "Ulhasnagar" },
  { name: "Vadodara" },
  { name: "Varanasi" },
  { name: "Vijayawada" },
  { name: "Visakhapatnam" },
  { name: "Warangal" },
],
  "IS": [
  { name: "Akranes" },
  { name: "Akureyri" },
  { name: "Garðabaer" },
  { name: "Hafnarfjorður" },
  { name: "Kopavogur" },
  { name: "Mosfellsbaer" },
  { name: "Reykjavik" },
  { name: "Selfoss" },
],
  "IT": [
  { name: "Acerra" },
  { name: "Acilia-Castel Fusano-Ostia Antica" },
  { name: "Acireale" },
  { name: "Afragola" },
  { name: "Alessandria" },
  { name: "Altamura" },
  { name: "Ancona" },
  { name: "Andria" },
  { name: "Arenella" },
  { name: "Arezzo" },
  { name: "Asti" },
  { name: "Aversa" },
  { name: "Bagheria" },
  { name: "Bari" },
  { name: "Barletta" },
  { name: "Bergamo" },
  { name: "Bisceglie" },
  { name: "Bitonto" },
  { name: "Bologna" },
  { name: "Bolzano" },
  { name: "Brescia" },
  { name: "Brindisi" },
  { name: "Busto Arsizio" },
  { name: "Cagliari" },
  { name: "Caltanissetta" },
  { name: "Carpi Centro" },
  { name: "Carrara" },
  { name: "Caserta" },
  { name: "Casoria" },
  { name: "Castellammare di Stabia" },
  { name: "Catania" },
  { name: "Catanzaro" },
  { name: "Cerignola" },
  { name: "Cesena" },
  { name: "Cinisello Balsamo" },
  { name: "Como" },
  { name: "Cosenza" },
  { name: "Cremona" },
  { name: "Ercolano" },
  { name: "Ferrara" },
  { name: "Florence" },
  { name: "Foggia" },
  { name: "Forli" },
  { name: "Fuorigrotta" },
  { name: "Gallarate" },
  { name: "Gela" },
  { name: "Genoa" },
  { name: "Giugliano in Campania" },
  { name: "Grosseto" },
  { name: "Guidonia Montecelio" },
  { name: "Imola" },
  { name: "La Spezia" },
  { name: "Lamezia Terme" },
  { name: "Latina" },
  { name: "Lecce" },
  { name: "Legnano" },
  { name: "Lido di Ostia" },
  { name: "Livorno" },
  { name: "Lucca" },
  { name: "Manfredonia" },
  { name: "Marano di Napoli" },
  { name: "Marsala" },
  { name: "Massa" },
  { name: "Matera" },
  { name: "Messina" },
  { name: "Mestre" },
  { name: "Milan" },
  { name: "Modena" },
  { name: "Molfetta" },
  { name: "Moncalieri" },
  { name: "Monza" },
  { name: "Naples" },
  { name: "Novara" },
  { name: "Padova" },
  { name: "Palermo" },
  { name: "Parma" },
  { name: "Pavia" },
  { name: "Perugia" },
  { name: "Pesaro" },
  { name: "Pescara" },
  { name: "Piacenza" },
  { name: "Pianura" },
  { name: "Pisa" },
  { name: "Pistoia" },
  { name: "Ponticelli" },
  { name: "Pordenone" },
  { name: "Portici" },
  { name: "Potenza" },
  { name: "Prato" },
  { name: "Quartu Sant'Elena" },
  { name: "Ragusa" },
  { name: "Ravenna" },
  { name: "Reggio Calabria" },
  { name: "Reggio nell'Emilia" },
  { name: "Rimini" },
  { name: "Rome" },
  { name: "Salerno" },
  { name: "San Carlo All'Arena" },
  { name: "San Severo" },
  { name: "Sassari" },
  { name: "Savona" },
  { name: "Scafati" },
  { name: "Sesto San Giovanni" },
  { name: "Siracusa" },
  { name: "Taranto" },
  { name: "Terni" },
  { name: "Torre del Greco" },
  { name: "Trani" },
  { name: "Trapani" },
  { name: "Trento" },
  { name: "Treviso" },
  { name: "Trieste" },
  { name: "Turin" },
  { name: "Udine" },
  { name: "Varese" },
  { name: "Venice" },
  { name: "Verona" },
  { name: "Vicenza" },
  { name: "Vigevano" },
  { name: "Vittoria" },
],
  "JP": [
  { name: "Ageoshimo" },
  { name: "Akashi" },
  { name: "Akita" },
  { name: "Amagasaki" },
  { name: "Anjo" },
  { name: "Aomori" },
  { name: "Asahikawa" },
  { name: "Atsugi" },
  { name: "Chiba" },
  { name: "Chigasaki" },
  { name: "Chofu" },
  { name: "Fuji" },
  { name: "Fujisawa" },
  { name: "Fukui-shi" },
  { name: "Fukuoka" },
  { name: "Fukushima" },
  { name: "Fukuyama" },
  { name: "Gifu-shi" },
  { name: "Hachinohe" },
  { name: "Hachioji" },
  { name: "Hadano" },
  { name: "Hakodate" },
  { name: "Hamamatsu" },
  { name: "Himeji" },
  { name: "Hirakata" },
  { name: "Hiratsuka" },
  { name: "Hirosaki" },
  { name: "Hiroshima" },
  { name: "Hitachi" },
  { name: "Honcho" },
  { name: "Ibaraki" },
  { name: "Ichihara" },
  { name: "Ichinomiya" },
  { name: "Itami" },
  { name: "Iwaki" },
  { name: "Izumi" },
  { name: "Joetsu" },
  { name: "Kagoshima" },
  { name: "Kakogawacho-honmachi" },
  { name: "Kamirenjaku" },
  { name: "Kanazawa" },
  { name: "Kashiwa" },
  { name: "Kasugai" },
  { name: "Kasukabe" },
  { name: "Kawagoe" },
  { name: "Kawaguchi" },
  { name: "Kawasaki" },
  { name: "Kishiwada" },
  { name: "Kitakyushu" },
  { name: "Kobe" },
  { name: "Kochi" },
  { name: "Kofu" },
  { name: "Koriyama" },
  { name: "Koshigaya" },
  { name: "Kumamoto" },
  { name: "Kurashiki" },
  { name: "Kure" },
  { name: "Kurume" },
  { name: "Kushiro" },
  { name: "Kyoto" },
  { name: "Machida" },
  { name: "Maebashi" },
  { name: "Matsudo" },
  { name: "Matsumoto" },
  { name: "Matsuyama" },
  { name: "Minamirinkan" },
  { name: "Minato" },
  { name: "Mito" },
  { name: "Miyazaki" },
  { name: "Morioka" },
  { name: "Nagano" },
  { name: "Nagaoka" },
  { name: "Nagasaki" },
  { name: "Nagoya" },
  { name: "Naha" },
  { name: "Nara-shi" },
  { name: "Neyagawa" },
  { name: "Niigata" },
  { name: "Nishi-Tokyo-shi" },
  { name: "Nishinomiya-hama" },
  { name: "Numazu" },
  { name: "Odawara" },
  { name: "Oita" },
  { name: "Okayama" },
  { name: "Okazaki" },
  { name: "Osaka" },
  { name: "Otsu" },
  { name: "Saitama" },
  { name: "Sakai" },
  { name: "Sakura" },
  { name: "Sapporo" },
  { name: "Sasebo" },
  { name: "Sendai" },
  { name: "Shimonoseki" },
  { name: "Shizuoka" },
  { name: "Soka" },
  { name: "Suita" },
  { name: "Suzuka" },
  { name: "Takamatsu" },
  { name: "Takarazuka" },
  { name: "Takasaki" },
  { name: "Takatsuki" },
  { name: "Tokorozawa" },
  { name: "Tokushima" },
  { name: "Tokyo" },
  { name: "Tomakomai" },
  { name: "Toyama" },
  { name: "Toyohashi" },
  { name: "Toyonaka" },
  { name: "Toyota" },
  { name: "Tsukuba" },
  { name: "Uji" },
  { name: "Utsunomiya" },
  { name: "Wakayama" },
  { name: "Yamagata" },
  { name: "Yao" },
  { name: "Yokkaichi" },
  { name: "Yokohama" },
  { name: "Yokosuka" },
  { name: "Yono" },
],
  "KR": [
  { name: "Andong" },
  { name: "Ansan-si" },
  { name: "Anseong" },
  { name: "Anyang-si" },
  { name: "Asan" },
  { name: "Boryeong" },
  { name: "Bucheon-si" },
  { name: "Busan" },
  { name: "Buyeo" },
  { name: "Changnyeong" },
  { name: "Changsu" },
  { name: "Changwon" },
  { name: "Cheonan" },
  { name: "Cheongju-si" },
  { name: "Cheongsong gun" },
  { name: "Chinch'on" },
  { name: "Chinju" },
  { name: "Chuncheon" },
  { name: "Daegu" },
  { name: "Daejeon" },
  { name: "Eisen" },
  { name: "Gaigeturi" },
  { name: "Ganghwa-gun" },
  { name: "Gangneung" },
  { name: "Gapyeong" },
  { name: "Gijang" },
  { name: "Gimcheon" },
  { name: "Gongju" },
  { name: "Goseong" },
  { name: "Goyang-si" },
  { name: "Gumi" },
  { name: "Gunsan" },
  { name: "Guri-si" },
  { name: "Gwangju" },
  { name: "Gyeongju" },
  { name: "Gyeongsan-si" },
  { name: "Haenam" },
  { name: "Hanam" },
  { name: "Hayang" },
  { name: "Heunghae" },
  { name: "Hongch’on" },
  { name: "Hongseong" },
  { name: "Hwacheon" },
  { name: "Hwado" },
  { name: "Hwaseong-si" },
  { name: "Hwasun" },
  { name: "Hwawon" },
  { name: "Icheon-si" },
  { name: "Iksan" },
  { name: "Imsil" },
  { name: "Incheon" },
  { name: "Jeju City" },
  { name: "Jeongeup" },
  { name: "Jeonju" },
  { name: "Jinan-gun" },
  { name: "Kimhae" },
  { name: "Kimje" },
  { name: "Kinzan" },
  { name: "Koch'ang" },
  { name: "Koesan" },
  { name: "Kosong" },
  { name: "Kunwi" },
  { name: "Kurye" },
  { name: "Kwangmyong" },
  { name: "Kwangyang" },
  { name: "Kyosai" },
  { name: "Masan" },
  { name: "Miryang" },
  { name: "Mokpo" },
  { name: "Muan" },
  { name: "Mungyeong" },
  { name: "Munsan" },
  { name: "Naeso" },
  { name: "Naju" },
  { name: "Namyangju" },
  { name: "Nangen" },
  { name: "Neietsu" },
  { name: "Nonsan" },
  { name: "Okcheon" },
  { name: "Osan" },
  { name: "Pohang" },
  { name: "Puan" },
  { name: "Pubal" },
  { name: "Sangju" },
  { name: "Santyoku" },
  { name: "Sejong" },
  { name: "Seogwipo" },
  { name: "Seonghwan" },
  { name: "Seongnam-si" },
  { name: "Seosan" },
  { name: "Seoul" },
  { name: "Sinan" },
  { name: "Sinhyeon" },
  { name: "Sokcho" },
  { name: "Suncheon" },
  { name: "Suwon" },
  { name: "T’aebaek" },
  { name: "Taesal-li" },
  { name: "Tangjin" },
  { name: "Tonghae" },
  { name: "Uijeongbu-si" },
  { name: "Ulsan" },
  { name: "Ungsang" },
  { name: "Wabu" },
  { name: "Waegwan" },
  { name: "Wanju" },
  { name: "Wonju" },
  { name: "Yanggu" },
  { name: "Yangju" },
  { name: "Yangp'yong" },
  { name: "Yangsan" },
  { name: "Yeoju" },
  { name: "Yeongam" },
  { name: "Yeongdong" },
  { name: "Yeonil" },
  { name: "Yeosu" },
  { name: "Yesan" },
  { name: "Yonmu" },
],
  "LI": [
  { name: "Balzers" },
  { name: "Schaan" },
  { name: "Triesen" },
],
  "LT": [
  { name: "Aleksotas" },
  { name: "Alytus" },
  { name: "Dainava (Kaunas)" },
  { name: "Eiguliai" },
  { name: "Fabijoniskes" },
  { name: "Jonava" },
  { name: "Justiniskes" },
  { name: "Kaunas" },
  { name: "Kedainiai" },
  { name: "Klaipeda" },
  { name: "Kretinga" },
  { name: "Lazdynai" },
  { name: "Marijampole" },
  { name: "Mazeikiai" },
  { name: "Naujamiestis" },
  { name: "Panevezys" },
  { name: "Pasilaiciai" },
  { name: "Plunge" },
  { name: "Radviliskis" },
  { name: "Seskine" },
  { name: "Siauliai" },
  { name: "Silainiai" },
  { name: "Silute" },
  { name: "Taurage" },
  { name: "Telsiai" },
  { name: "Ukmerge" },
  { name: "Utena" },
  { name: "Vilkpede" },
  { name: "Vilnius" },
  { name: "Visaginas" },
],
  "LU": [
  { name: "Belvaux" },
  { name: "Bertrange" },
  { name: "Bettembourg" },
  { name: "Diekirch" },
  { name: "Differdange" },
  { name: "Dudelange" },
  { name: "Esch-sur-Alzette" },
  { name: "Ettelbruck" },
  { name: "Luxembourg" },
  { name: "Mamer" },
  { name: "Petange" },
  { name: "Schifflange" },
  { name: "Strassen" },
],
  "LV": [
  { name: "Aizkraukle" },
  { name: "Bauska" },
  { name: "Bolderaja" },
  { name: "Cesis" },
  { name: "Daugavgriva" },
  { name: "Daugavpils" },
  { name: "Dobele" },
  { name: "Gulbene" },
  { name: "Jekabpils" },
  { name: "Jelgava" },
  { name: "Jurmala" },
  { name: "Kraslava" },
  { name: "Kuldiga" },
  { name: "Liepaja" },
  { name: "Limbazi" },
  { name: "Livani" },
  { name: "Ludza" },
  { name: "Madona" },
  { name: "Ogre" },
  { name: "Olaine" },
  { name: "Preili" },
  { name: "Rezekne" },
  { name: "Riga" },
  { name: "Salaspils" },
  { name: "Saldus" },
  { name: "Sigulda" },
  { name: "Talsi" },
  { name: "Tukums" },
  { name: "Valmiera" },
  { name: "Ventspils" },
],
  "MC": [
  { name: "La Condamine" },
  { name: "Monaco" },
  { name: "Monte-Carlo" },
],
  "MD": [
  { name: "Balti" },
  { name: "Bender" },
  { name: "Bilicenii Vechi" },
  { name: "Briceni" },
  { name: "Cahul" },
  { name: "Calarasi" },
  { name: "Causeni" },
  { name: "Ceadir-Lunga" },
  { name: "Chisinau" },
  { name: "Cimislia" },
  { name: "Comrat" },
  { name: "Drochia" },
  { name: "Dubasari" },
  { name: "Edinet" },
  { name: "Falesti" },
  { name: "Floresti" },
  { name: "Hincesti" },
  { name: "Ialoveni" },
  { name: "Leova" },
  { name: "Orhei" },
  { name: "Ribnita" },
  { name: "Riscani" },
  { name: "Singerei" },
  { name: "Slobozia" },
  { name: "Soroca" },
  { name: "Straseni" },
  { name: "Taraclia" },
  { name: "Tiraspol" },
  { name: "Ungheni" },
  { name: "Vulcanesti" },
],
  "ME": [
  { name: "Bar" },
  { name: "Berane" },
  { name: "Bijelo Polje" },
  { name: "Budva" },
  { name: "Cetinje" },
  { name: "Danilovgrad" },
  { name: "Dobrota" },
  { name: "Herceg Novi" },
  { name: "Kotor" },
  { name: "Niksic" },
  { name: "Pljevlja" },
  { name: "Podgorica" },
  { name: "Rozaje" },
  { name: "Tivat" },
  { name: "Ulcinj" },
],
  "MK": [
  { name: "Bitola" },
  { name: "Butel" },
  { name: "Cair" },
  { name: "Centar Zupa" },
  { name: "Gevgelija" },
  { name: "Gjorce Petro" },
  { name: "Gostivar" },
  { name: "Kavadarci" },
  { name: "Kicevo" },
  { name: "Kisela Voda" },
  { name: "Kochani" },
  { name: "Kriva Palanka" },
  { name: "Kumanovo" },
  { name: "Lipkovo" },
  { name: "Negotino" },
  { name: "Ohrid" },
  { name: "Prilep" },
  { name: "Radovis" },
  { name: "Saraj" },
  { name: "Shtip" },
  { name: "Skopje" },
  { name: "Struga" },
  { name: "Strumica" },
  { name: "Studenicane" },
  { name: "Suto Orizare" },
  { name: "Tearce" },
  { name: "Tetovo" },
  { name: "Veles" },
  { name: "Vinica" },
  { name: "Zelino" },
],
  "MT": [
  { name: "Attard" },
  { name: "Birkirkara" },
  { name: "Birzebbuga" },
  { name: "Cospicua" },
  { name: "Fgura" },
  { name: "Gzira" },
  { name: "Ħamrun" },
  { name: "Haz-Zebbug" },
  { name: "Imsida" },
  { name: "Marsa" },
  { name: "Marsaskala" },
  { name: "Mellieħa" },
  { name: "Mosta" },
  { name: "Naxxar" },
  { name: "Paola" },
  { name: "Qormi" },
  { name: "Rabat" },
  { name: "Saint John" },
  { name: "San Giljan" },
  { name: "San Pawl il-Baħar" },
  { name: "Santa Venera" },
  { name: "Siggiewi" },
  { name: "Sliema" },
  { name: "Swieqi" },
  { name: "Tarxien" },
  { name: "Valletta" },
  { name: "Victoria" },
  { name: "Zabbar" },
  { name: "Zejtun" },
  { name: "Zurrieq" },
],
  "NL": [
  { name: "'s-Hertogenbosch" },
  { name: "Alkmaar" },
  { name: "Almelo" },
  { name: "Almere Stad" },
  { name: "Alphen aan den Rijn" },
  { name: "Amersfoort" },
  { name: "Amstelveen" },
  { name: "Amsterdam" },
  { name: "Amsterdam-Zuidoost" },
  { name: "Apeldoorn" },
  { name: "Arnhem" },
  { name: "Breda" },
  { name: "Delft" },
  { name: "Deventer" },
  { name: "Dordrecht" },
  { name: "Eindhoven" },
  { name: "Enschede" },
  { name: "Gouda" },
  { name: "Groningen" },
  { name: "Haarlem" },
  { name: "Heerlen" },
  { name: "Helmond" },
  { name: "Hengelo" },
  { name: "Hilversum" },
  { name: "Hoofddorp" },
  { name: "Leeuwarden" },
  { name: "Leiden" },
  { name: "Lelystad" },
  { name: "Maastricht" },
  { name: "Nijmegen" },
  { name: "Oss" },
  { name: "Purmerend" },
  { name: "Roosendaal" },
  { name: "Rotterdam" },
  { name: "Schiedam" },
  { name: "Spijkenisse" },
  { name: "The Hague" },
  { name: "Tilburg" },
  { name: "Utrecht" },
  { name: "Venlo" },
  { name: "Vlaardingen" },
  { name: "Zaandam" },
  { name: "Zaanstad" },
  { name: "Zoetermeer" },
  { name: "Zwolle" },
],
  "NO": [
  { name: "Alesund" },
  { name: "Alta" },
  { name: "Arendal" },
  { name: "Asker" },
  { name: "Askim" },
  { name: "Askoy" },
  { name: "Bergen" },
  { name: "Bodo" },
  { name: "Drammen" },
  { name: "Drobak" },
  { name: "Elverum" },
  { name: "Fredrikstad" },
  { name: "Gjovik" },
  { name: "Halden" },
  { name: "Hamar" },
  { name: "Harstad" },
  { name: "Haugesund" },
  { name: "Honefoss" },
  { name: "Horten" },
  { name: "Jessheim" },
  { name: "Kongsberg" },
  { name: "Kongsvinger" },
  { name: "Kristiansand" },
  { name: "Kristiansund" },
  { name: "Larvik" },
  { name: "Lillehammer" },
  { name: "Lillestrom" },
  { name: "Mo i Rana" },
  { name: "Molde" },
  { name: "Moss" },
  { name: "Narvik" },
  { name: "Oslo" },
  { name: "Porsgrunn" },
  { name: "Sandefjord" },
  { name: "Sandnes" },
  { name: "Sarpsborg" },
  { name: "Ski" },
  { name: "Skien" },
  { name: "Stavanger" },
  { name: "Steinkjer" },
  { name: "Stjordalshalsen" },
  { name: "Tonsberg" },
  { name: "Tromso" },
  { name: "Trondheim" },
  { name: "Ytrebygda" },
],
  "PL": [
  { name: "Bedzin" },
  { name: "Belchatow" },
  { name: "Bemowo" },
  { name: "Biala Podlaska" },
  { name: "Bialoleka" },
  { name: "Bialystok" },
  { name: "Bielany" },
  { name: "Bielsko-Biala" },
  { name: "Bydgoszcz" },
  { name: "Bytom" },
  { name: "Chelm" },
  { name: "Chorzow" },
  { name: "Ciechanow" },
  { name: "Czestochowa" },
  { name: "Dabrowa Gornicza" },
  { name: "Debica" },
  { name: "Elblag" },
  { name: "Elk" },
  { name: "Fordon" },
  { name: "Gdansk" },
  { name: "Gdynia" },
  { name: "Gliwice" },
  { name: "Glogow" },
  { name: "Gniezno" },
  { name: "Gorzow Wielkopolski" },
  { name: "Grudziadz" },
  { name: "Inowroclaw" },
  { name: "Jastrzebie Zdroj" },
  { name: "Jaworzno" },
  { name: "Jelenia Gora" },
  { name: "Kalisz" },
  { name: "Katowice" },
  { name: "Kedzierzyn-Kozle" },
  { name: "Kielce" },
  { name: "Kolobrzeg" },
  { name: "Konin" },
  { name: "Koszalin" },
  { name: "Krakow" },
  { name: "Krosno" },
  { name: "Kutno" },
  { name: "Legionowo" },
  { name: "Legnica" },
  { name: "Leszno" },
  { name: "Lodz" },
  { name: "Lomza" },
  { name: "Lubin" },
  { name: "Lublin" },
  { name: "Mielec" },
  { name: "Mokotow" },
  { name: "Myslowice" },
  { name: "Nowy Sacz" },
  { name: "Nysa" },
  { name: "Ochota" },
  { name: "Olsztyn" },
  { name: "Opole" },
  { name: "Ostroleka" },
  { name: "Ostrow Wielkopolski" },
  { name: "Ostrowiec Swietokrzyski" },
  { name: "Otwock" },
  { name: "Pabianice" },
  { name: "Piekary Slaskie" },
  { name: "Pila" },
  { name: "Piotrkow Trybunalski" },
  { name: "Plock" },
  { name: "Poznan" },
  { name: "Praga Polnoc" },
  { name: "Praga Poludnie" },
  { name: "Pruszkow" },
  { name: "Przemysl" },
  { name: "Pulawy" },
  { name: "Raciborz" },
  { name: "Radom" },
  { name: "Radomsko" },
  { name: "Rejon placu Swietego Macieja" },
  { name: "Ruda Slaska" },
  { name: "Rumia" },
  { name: "Rybnik" },
  { name: "Rzeszow" },
  { name: "Siedlce" },
  { name: "Siemianowice Slaskie" },
  { name: "Sieradz" },
  { name: "Skarzysko-Kamienna" },
  { name: "Skierniewice" },
  { name: "Slupsk" },
  { name: "Sosnowiec" },
  { name: "Srodmiescie" },
  { name: "Stalowa Wola" },
  { name: "Starachowice" },
  { name: "Stargard" },
  { name: "Starogard Gdanski" },
  { name: "Suwalki" },
  { name: "Swidnica" },
  { name: "Swietochlowice" },
  { name: "Szczecin" },
  { name: "Targowek" },
  { name: "Tarnobrzeg" },
  { name: "Tarnow" },
  { name: "Tarnowskie Gory" },
  { name: "Tczew" },
  { name: "Tomaszow Mazowiecki" },
  { name: "Torun" },
  { name: "Tychy" },
  { name: "Ursus" },
  { name: "Ursynow" },
  { name: "Walbrzych" },
  { name: "Warsaw" },
  { name: "Wawer" },
  { name: "Wejherowo" },
  { name: "Wloclawek" },
  { name: "Wodzislaw Slaski" },
  { name: "Wola" },
  { name: "Wroclaw" },
  { name: "Zabrze" },
  { name: "Zamosc" },
  { name: "Zawiercie" },
  { name: "Zdunska Wola" },
  { name: "Zgierz" },
  { name: "Zielona Gora" },
  { name: "Zoliborz" },
  { name: "Zory" },
],
  "PT": [
  { name: "Alcabideche" },
  { name: "Algueirao" },
  { name: "Almada" },
  { name: "Amadora" },
  { name: "Amora" },
  { name: "Aveiro" },
  { name: "Barreiro" },
  { name: "Beja" },
  { name: "Benfica" },
  { name: "Braga" },
  { name: "Braganca" },
  { name: "Cacem" },
  { name: "Cascais" },
  { name: "Castelo Branco" },
  { name: "Coimbra" },
  { name: "Corroios" },
  { name: "Ermesinde" },
  { name: "Espinho" },
  { name: "Esposende" },
  { name: "Evora" },
  { name: "Faro" },
  { name: "Felgueiras" },
  { name: "Figueira da Foz" },
  { name: "Funchal" },
  { name: "Guimaraes" },
  { name: "Leiria" },
  { name: "Lisbon" },
  { name: "Loures" },
  { name: "Maia" },
  { name: "Monsanto" },
  { name: "Odivelas" },
  { name: "Oeiras" },
  { name: "Olivais" },
  { name: "Ponte de Lima" },
  { name: "Portimao" },
  { name: "Porto" },
  { name: "Queluz" },
  { name: "Rio de Mouro" },
  { name: "Rio Tinto" },
  { name: "Santo Antonio dos Olivais" },
  { name: "Sao Domingos de Rana" },
  { name: "Sesimbra" },
  { name: "Setubal" },
  { name: "Viana do Castelo" },
  { name: "Vila Nova de Gaia" },
],
  "RO": [
  { name: "Alba Iulia" },
  { name: "Arad" },
  { name: "Bacau" },
  { name: "Baia Mare" },
  { name: "Barlad" },
  { name: "Bistrita" },
  { name: "Botosani" },
  { name: "Braila" },
  { name: "Brasov" },
  { name: "Bucharest" },
  { name: "Buzau" },
  { name: "Cluj-Napoca" },
  { name: "Constanta" },
  { name: "Craiova" },
  { name: "Deva" },
  { name: "Drobeta-Turnu Severin" },
  { name: "Focsani" },
  { name: "Galati" },
  { name: "Giurgiu" },
  { name: "Hunedoara" },
  { name: "Iasi" },
  { name: "Oradea" },
  { name: "Piatra Neamt" },
  { name: "Pitesti" },
  { name: "Ploiesti" },
  { name: "Ramnicu Valcea" },
  { name: "Resita" },
  { name: "Roman" },
  { name: "Satu Mare" },
  { name: "Sector 1" },
  { name: "Sector 2" },
  { name: "Sector 3" },
  { name: "Sector 4" },
  { name: "Sector 5" },
  { name: "Sector 6" },
  { name: "Sibiu" },
  { name: "Slatina" },
  { name: "Suceava" },
  { name: "Targoviste" },
  { name: "Targu Jiu" },
  { name: "Targu-Mures" },
  { name: "Timisoara" },
  { name: "Tulcea" },
  { name: "Vaslui" },
  { name: "Zalau" },
],
  "RS": [
  { name: "Apatin" },
  { name: "Arandelovac" },
  { name: "Backa Palanka" },
  { name: "Becej" },
  { name: "Belgrade" },
  { name: "Bor" },
  { name: "Cacak" },
  { name: "Cuprija" },
  { name: "Gornji Milanovac" },
  { name: "Indija" },
  { name: "Jagodina" },
  { name: "Kikinda" },
  { name: "Knjazevac" },
  { name: "Kragujevac" },
  { name: "Kraljevo" },
  { name: "Krusevac" },
  { name: "Lazarevac" },
  { name: "Leskovac" },
  { name: "Negotin" },
  { name: "Nis" },
  { name: "Novi Pazar" },
  { name: "Novi Sad" },
  { name: "Obrenovac" },
  { name: "Pancevo" },
  { name: "Pirot" },
  { name: "Pozarevac" },
  { name: "Prokuplje" },
  { name: "Ruma" },
  { name: "Sabac" },
  { name: "Senta" },
  { name: "Smederevo" },
  { name: "Smederevska Palanka" },
  { name: "Sombor" },
  { name: "Sremcica" },
  { name: "Sremska Mitrovica" },
  { name: "Subotica" },
  { name: "Trstenik" },
  { name: "Uzice" },
  { name: "Valjevo" },
  { name: "Vranje" },
  { name: "Vrbas" },
  { name: "Vrsac" },
  { name: "Zajecar" },
  { name: "Zemun" },
  { name: "Zrenjanin" },
],
  "RU": [
  { name: "Abakan" },
  { name: "Angarsk" },
  { name: "Arkhangel’sk" },
  { name: "Armavir" },
  { name: "Astrakhan" },
  { name: "Balakovo" },
  { name: "Barnaul" },
  { name: "Belgorod" },
  { name: "Berezniki" },
  { name: "Biysk" },
  { name: "Blagoveshchensk" },
  { name: "Bratsk" },
  { name: "Bryansk" },
  { name: "Centralniy" },
  { name: "Cheboksary" },
  { name: "Chelyabinsk" },
  { name: "Cherepovets" },
  { name: "Chita" },
  { name: "Dzerzhinsk" },
  { name: "Engel’s" },
  { name: "Groznyy" },
  { name: "Irkutsk" },
  { name: "Ivanovo" },
  { name: "Izhevsk" },
  { name: "Kaliningrad" },
  { name: "Kalininskiy" },
  { name: "Kaluga" },
  { name: "Kamensk-Ural’skiy" },
  { name: "Kazan" },
  { name: "Kemerovo" },
  { name: "Khabarovsk" },
  { name: "Khabarovsk Vtoroy" },
  { name: "Khimki" },
  { name: "Kirov" },
  { name: "Komsomolsk-on-Amur" },
  { name: "Kostroma" },
  { name: "Krasnodar" },
  { name: "Krasnogvargeisky" },
  { name: "Krasnoyarsk" },
  { name: "Kurgan" },
  { name: "Kursk" },
  { name: "Lipetsk" },
  { name: "Lyublino" },
  { name: "Magnitogorsk" },
  { name: "Makhachkala" },
  { name: "Mar’ino" },
  { name: "Miass" },
  { name: "Moscow" },
  { name: "Murmansk" },
  { name: "Mytishchi" },
  { name: "Naberezhnyye Chelny" },
  { name: "Nal’chik" },
  { name: "Nazran’" },
  { name: "Nizhnekamsk" },
  { name: "Nizhnevartovsk" },
  { name: "Nizhniy Novgorod" },
  { name: "Nizhny Tagil" },
  { name: "Novocherkassk" },
  { name: "Novokuznetsk" },
  { name: "Novorossiysk" },
  { name: "Novosibirsk" },
  { name: "Omsk" },
  { name: "Orel" },
  { name: "Orenburg" },
  { name: "Orsk" },
  { name: "Penza" },
  { name: "Perm" },
  { name: "Petropavlovsk-Kamchatsky" },
  { name: "Petrozavodsk" },
  { name: "Podolsk" },
  { name: "Prokop’yevsk" },
  { name: "Pskov" },
  { name: "Rostov-na-Donu" },
  { name: "Rubtsovsk" },
  { name: "Ryazan’" },
  { name: "Rybinsk" },
  { name: "Saint Petersburg" },
  { name: "Samara" },
  { name: "Saransk" },
  { name: "Saratov" },
  { name: "Severnyy" },
  { name: "Severodvinsk" },
  { name: "Shakhty" },
  { name: "Smolensk" },
  { name: "Sochi" },
  { name: "Staryy Oskol" },
  { name: "Stavropol’" },
  { name: "Sterlitamak" },
  { name: "Surgut" },
  { name: "Syktyvkar" },
  { name: "Syzran’" },
  { name: "Taganrog" },
  { name: "Tambov" },
  { name: "Tol’yatti" },
  { name: "Tomsk" },
  { name: "Tula" },
  { name: "Tver" },
  { name: "Tyumen" },
  { name: "Ufa" },
  { name: "Ulan-Ude" },
  { name: "Ulyanovsk" },
  { name: "Vasyl'evsky Ostrov" },
  { name: "Velikiy Novgorod" },
  { name: "Vladikavkaz" },
  { name: "Vladimir" },
  { name: "Vladivostok" },
  { name: "Volgodonsk" },
  { name: "Volgograd" },
  { name: "Vologda" },
  { name: "Volzhskiy" },
  { name: "Voronezh" },
  { name: "Vykhino-Zhulebino" },
  { name: "Yakutsk" },
  { name: "Yaroslavl" },
  { name: "Yasenevo" },
  { name: "Yekaterinburg" },
  { name: "Yoshkar-Ola" },
  { name: "Yuzhno-Sakhalinsk" },
  { name: "Zelenograd" },
  { name: "Zlatoust" },
],
  "SE": [
  { name: "Boras" },
  { name: "Borlange" },
  { name: "Bromma" },
  { name: "Eskilstuna" },
  { name: "Falun" },
  { name: "Gavle" },
  { name: "Gothenburg" },
  { name: "Halmstad" },
  { name: "Haninge" },
  { name: "Helsingborg" },
  { name: "Huddinge" },
  { name: "Jonkoping" },
  { name: "Kalmar" },
  { name: "Karlskrona" },
  { name: "Karlstad" },
  { name: "Kristianstad" },
  { name: "Kungsholmen" },
  { name: "Lidingo" },
  { name: "Linkoping" },
  { name: "Lulea" },
  { name: "Lund" },
  { name: "Malmo" },
  { name: "Molndal" },
  { name: "Norrkoping" },
  { name: "Orebro" },
  { name: "Ostermalm" },
  { name: "Ostersund" },
  { name: "Skelleftea" },
  { name: "Skovde" },
  { name: "Sodermalm" },
  { name: "Sodertalje" },
  { name: "Sollentuna" },
  { name: "Solna" },
  { name: "Stockholm" },
  { name: "Sundsvall" },
  { name: "Taby" },
  { name: "Trollhattan" },
  { name: "Tumba" },
  { name: "Uddevalla" },
  { name: "Umea" },
  { name: "Upplands Vasby" },
  { name: "Uppsala" },
  { name: "Vasastan" },
  { name: "Vasteras" },
  { name: "Vaxjo" },
],
  "SI": [
  { name: "Celje" },
  { name: "Domzale" },
  { name: "Izola" },
  { name: "Jesenice" },
  { name: "Kamnik" },
  { name: "Koper" },
  { name: "Kranj" },
  { name: "Ljubljana" },
  { name: "Maribor" },
  { name: "Murska Sobota" },
  { name: "Nova Gorica" },
  { name: "Novo Mesto" },
  { name: "Ptuj" },
  { name: "Skofja Loka" },
  { name: "Trbovlje" },
  { name: "Velenje" },
],
  "SK": [
  { name: "Banovce nad Bebravou" },
  { name: "Banska Bystrica" },
  { name: "Bardejov" },
  { name: "Bratislava" },
  { name: "Brezno" },
  { name: "Cadca" },
  { name: "Dolny Kubin" },
  { name: "Dubnica nad Vahom" },
  { name: "Dunajska Streda" },
  { name: "Handlova" },
  { name: "Hlohovec" },
  { name: "Humenne" },
  { name: "Komarno" },
  { name: "Kosice" },
  { name: "Levice" },
  { name: "Liptovsky Mikulas" },
  { name: "Lucenec" },
  { name: "Malacky" },
  { name: "Martin" },
  { name: "Michalovce" },
  { name: "Nitra" },
  { name: "Nove Mesto nad Vahom" },
  { name: "Nove Zamky" },
  { name: "Partizanske" },
  { name: "Pezinok" },
  { name: "Piestany" },
  { name: "Poprad" },
  { name: "Povazska Bystrica" },
  { name: "Presov" },
  { name: "Prievidza" },
  { name: "Puchov" },
  { name: "Rimavska Sobota" },
  { name: "Roznava" },
  { name: "Ruzomberok" },
  { name: "Sala" },
  { name: "Senica" },
  { name: "Snina" },
  { name: "Spisska Nova Ves" },
  { name: "Trebisov" },
  { name: "Trencin" },
  { name: "Trnava" },
  { name: "Vranov nad Toplou" },
  { name: "Ziar nad Hronom" },
  { name: "Zilina" },
  { name: "Zvolen" },
],
  "SM": [
  { name: "Borgo Maggiore" },
  { name: "San Marino" },
  { name: "Serravalle" },
],
  "TR": [
  { name: "Adana" },
  { name: "Adiyaman" },
  { name: "Afyonkarahisar" },
  { name: "Agri" },
  { name: "Aksaray" },
  { name: "Amasya" },
  { name: "Ankara" },
  { name: "Antalya" },
  { name: "Ardahan" },
  { name: "Artvin" },
  { name: "Aydin" },
  { name: "Balikesir" },
  { name: "Bartin" },
  { name: "Batman" },
  { name: "Bayburt" },
  { name: "Bilecik" },
  { name: "Bingol" },
  { name: "Bitlis" },
  { name: "Bolu" },
  { name: "Burdur" },
  { name: "Bursa" },
  { name: "Canakkale" },
  { name: "Cankiri" },
  { name: "Corum" },
  { name: "Denizli" },
  { name: "Diyarbakir" },
  { name: "Duzce" },
  { name: "Edirne" },
  { name: "Elazig" },
  { name: "Erzincan" },
  { name: "Erzurum" },
  { name: "Eskisehir" },
  { name: "Gaziantep" },
  { name: "Giresun" },
  { name: "Gumushane" },
  { name: "Hakkari" },
  { name: "Hatay" },
  { name: "Igdir" },
  { name: "Isparta" },
  { name: "Istanbul" },
  { name: "Izmir" },
  { name: "Kahramanmaras" },
  { name: "Karabuk" },
  { name: "Karaman" },
  { name: "Kars" },
  { name: "Kastamonu" },
  { name: "Kayseri" },
  { name: "Kilis" },
  { name: "Kirikkale" },
  { name: "Kirklareli" },
  { name: "Kirsehir" },
  { name: "Kocaeli" },
  { name: "Konya" },
  { name: "Kutahya" },
  { name: "Malatya" },
  { name: "Manisa" },
  { name: "Mardin" },
  { name: "Mersin" },
  { name: "Mugla" },
  { name: "Mus" },
  { name: "Nevsehir" },
  { name: "Nigde" },
  { name: "Ordu" },
  { name: "Osmaniye" },
  { name: "Rize" },
  { name: "Sakarya" },
  { name: "Samsun" },
  { name: "Sanliurfa" },
  { name: "Siirt" },
  { name: "Sinop" },
  { name: "Sirnak" },
  { name: "Sivas" },
  { name: "Tekirdag" },
  { name: "Tokat" },
  { name: "Trabzon" },
  { name: "Tunceli" },
  { name: "Usak" },
  { name: "Van" },
  { name: "Yalova" },
  { name: "Yozgat" },
  { name: "Zonguldak" },
],
  "TR-NC": [
  { name: "Famagusta" },
  { name: "Kyrenia" },
  { name: "Lefka" },
  { name: "Morphou" },
  { name: "Nicosia" },
],
  "UA": [
  { name: "Alchevs’k" },
  { name: "Berdyansk" },
  { name: "Bila Tserkva" },
  { name: "Cherkasy" },
  { name: "Chernihiv" },
  { name: "Chernivtsi" },
  { name: "Dnipro" },
  { name: "Donetsk" },
  { name: "Horlivka" },
  { name: "Ivano-Frankivsk" },
  { name: "Kamianske" },
  { name: "Kerch" },
  { name: "Kharkiv" },
  { name: "Kherson" },
  { name: "Khmelnytskyi" },
  { name: "Kramators’k" },
  { name: "Kremenchuk" },
  { name: "Kropyvnytskyi" },
  { name: "Kryvyi Rih" },
  { name: "Kyiv" },
  { name: "Luhansk" },
  { name: "Lutsk" },
  { name: "Lviv" },
  { name: "Lysychans’k" },
  { name: "Makiyivka" },
  { name: "Mariupol" },
  { name: "Melitopol" },
  { name: "Mykolayiv" },
  { name: "Nikopol" },
  { name: "Odessa" },
  { name: "Pavlohrad" },
  { name: "Poltava" },
  { name: "Rivne" },
  { name: "Sevastopol" },
  { name: "Simferopol" },
  { name: "Sloviansk" },
  { name: "Sumy" },
  { name: "Syevyerodonets’k" },
  { name: "Ternopil" },
  { name: "Uzhgorod" },
  { name: "Vinnytsia" },
  { name: "Yenakiyeve" },
  { name: "Yevpatoriya" },
  { name: "Zaporizhia" },
  { name: "Zhytomyr" },
],
  "US": [],
  "VA": [
  { name: "Vatican City" },
],
  "XK": [
  { name: "Decan" },
  { name: "Dragash" },
  { name: "Ferizaj" },
  { name: "Gjakova" },
  { name: "Gjakove" },
  { name: "Gjilan" },
  { name: "Glogovac" },
  { name: "Hani i Elezit" },
  { name: "Istok" },
  { name: "Kacanik" },
  { name: "Kamenica" },
  { name: "Klina" },
  { name: "Kosovo Polje" },
  { name: "Leposaviq" },
  { name: "Lipljan" },
  { name: "Llazice" },
  { name: "Mitrovica" },
  { name: "Mitrovice" },
  { name: "Novo Brdo" },
  { name: "Obiliq" },
  { name: "Orahovac" },
  { name: "Pec" },
  { name: "Peja" },
  { name: "Podujeva" },
  { name: "Podujevo" },
  { name: "Pristina" },
  { name: "Prizren" },
  { name: "Shtime" },
  { name: "Strpce" },
  { name: "Suva Reka" },
],
};

export const US_CITIES_BY_STATE: UsCitiesByState = {
  "AK": [
  { name: "Anchorage" },
  { name: "Fairbanks" },
  { name: "Homer" },
  { name: "Juneau" },
  { name: "Kenai" },
  { name: "Ketchikan" },
  { name: "Kodiak" },
  { name: "Palmer" },
  { name: "Sitka" },
  { name: "Wasilla" },
],
  "AL": [
  { name: "Auburn" },
  { name: "Birmingham" },
  { name: "Decatur" },
  { name: "Dothan" },
  { name: "Hoover" },
  { name: "Huntsville" },
  { name: "Madison" },
  { name: "Mobile" },
  { name: "Montgomery" },
  { name: "Tuscaloosa" },
],
  "AR": [
  { name: "Bentonville" },
  { name: "Conway" },
  { name: "Fayetteville" },
  { name: "Fort Smith" },
  { name: "Jonesboro" },
  { name: "Little Rock" },
  { name: "North Little Rock" },
  { name: "Pine Bluff" },
  { name: "Rogers" },
  { name: "Springdale" },
],
  "AZ": [
  { name: "Chandler" },
  { name: "Flagstaff" },
  { name: "Gilbert" },
  { name: "Glendale" },
  { name: "Mesa" },
  { name: "Peoria" },
  { name: "Phoenix" },
  { name: "Scottsdale" },
  { name: "Surprise" },
  { name: "Tempe" },
  { name: "Tucson" },
  { name: "Yuma" },
],
  "CA": [
  { name: "Anaheim" },
  { name: "Bakersfield" },
  { name: "Fresno" },
  { name: "Irvine" },
  { name: "Long Beach" },
  { name: "Los Angeles" },
  { name: "Oakland" },
  { name: "Riverside" },
  { name: "Sacramento" },
  { name: "San Bernardino" },
  { name: "San Diego" },
  { name: "San Francisco" },
  { name: "San Jose" },
  { name: "Santa Ana" },
  { name: "Stockton" },
],
  "CO": [
  { name: "Arvada" },
  { name: "Aurora" },
  { name: "Boulder" },
  { name: "Colorado Springs" },
  { name: "Denver" },
  { name: "Fort Collins" },
  { name: "Greeley" },
  { name: "Lakewood" },
  { name: "Pueblo" },
  { name: "Thornton" },
  { name: "Westminster" },
],
  "CT": [
  { name: "Bridgeport" },
  { name: "Bristol" },
  { name: "Danbury" },
  { name: "Hartford" },
  { name: "Meriden" },
  { name: "New Britain" },
  { name: "New Haven" },
  { name: "Norwalk" },
  { name: "Stamford" },
  { name: "Waterbury" },
],
  "DE": [
  { name: "Dover" },
  { name: "Georgetown" },
  { name: "Middletown" },
  { name: "Milford" },
  { name: "Newark" },
  { name: "Seaford" },
  { name: "Smyrna" },
  { name: "Wilmington" },
],
  "FL": [
  { name: "Cape Coral" },
  { name: "Fort Lauderdale" },
  { name: "Gainesville" },
  { name: "Hialeah" },
  { name: "Hollywood" },
  { name: "Jacksonville" },
  { name: "Miami" },
  { name: "Miramar" },
  { name: "Orlando" },
  { name: "Pembroke Pines" },
  { name: "Port St. Lucie" },
  { name: "St. Petersburg" },
  { name: "Tallahassee" },
  { name: "Tampa" },
],
  "GA": [
  { name: "Albany" },
  { name: "Athens" },
  { name: "Atlanta" },
  { name: "Augusta" },
  { name: "Columbus" },
  { name: "Johns Creek" },
  { name: "Macon" },
  { name: "Roswell" },
  { name: "Sandy Springs" },
  { name: "Savannah" },
  { name: "Warner Robins" },
],
  "HI": [
  { name: "Ewa Gentry" },
  { name: "Hilo" },
  { name: "Honolulu" },
  { name: "Kahului" },
  { name: "Kailua" },
  { name: "Kaneohe" },
  { name: "Mililani" },
  { name: "Pearl City" },
  { name: "Waipahu" },
],
  "IA": [
  { name: "Ames" },
  { name: "Cedar Rapids" },
  { name: "Council Bluffs" },
  { name: "Davenport" },
  { name: "Des Moines" },
  { name: "Dubuque" },
  { name: "Iowa City" },
  { name: "Sioux City" },
  { name: "Waterloo" },
  { name: "West Des Moines" },
],
  "ID": [
  { name: "Boise" },
  { name: "Caldwell" },
  { name: "Coeur d'Alene" },
  { name: "Idaho Falls" },
  { name: "Lewiston" },
  { name: "Meridian" },
  { name: "Nampa" },
  { name: "Pocatello" },
  { name: "Twin Falls" },
],
  "IL": [
  { name: "Aurora" },
  { name: "Bloomington" },
  { name: "Champaign" },
  { name: "Chicago" },
  { name: "Cicero" },
  { name: "Elgin" },
  { name: "Joliet" },
  { name: "Naperville" },
  { name: "Peoria" },
  { name: "Rockford" },
  { name: "Springfield" },
  { name: "Waukegan" },
],
  "IN": [
  { name: "Bloomington" },
  { name: "Carmel" },
  { name: "Evansville" },
  { name: "Fishers" },
  { name: "Fort Wayne" },
  { name: "Gary" },
  { name: "Hammond" },
  { name: "Indianapolis" },
  { name: "Lafayette" },
  { name: "Muncie" },
  { name: "South Bend" },
],
  "KS": [
  { name: "Kansas City" },
  { name: "Lawrence" },
  { name: "Lenexa" },
  { name: "Manhattan" },
  { name: "Olathe" },
  { name: "Overland Park" },
  { name: "Salina" },
  { name: "Shawnee" },
  { name: "Topeka" },
  { name: "Wichita" },
],
  "KY": [
  { name: "Bowling Green" },
  { name: "Covington" },
  { name: "Florence" },
  { name: "Frankfort" },
  { name: "Georgetown" },
  { name: "Hopkinsville" },
  { name: "Lexington" },
  { name: "Louisville" },
  { name: "Owensboro" },
  { name: "Richmond" },
],
  "LA": [
  { name: "Alexandria" },
  { name: "Baton Rouge" },
  { name: "Bossier City" },
  { name: "Kenner" },
  { name: "Lafayette" },
  { name: "Lake Charles" },
  { name: "Metairie" },
  { name: "Monroe" },
  { name: "New Orleans" },
  { name: "Shreveport" },
],
  "MA": [
  { name: "Boston" },
  { name: "Brockton" },
  { name: "Cambridge" },
  { name: "Fall River" },
  { name: "Lowell" },
  { name: "Lynn" },
  { name: "New Bedford" },
  { name: "Quincy" },
  { name: "Somerville" },
  { name: "Springfield" },
  { name: "Worcester" },
],
  "MD": [
  { name: "Annapolis" },
  { name: "Baltimore" },
  { name: "Bowie" },
  { name: "College Park" },
  { name: "Frederick" },
  { name: "Gaithersburg" },
  { name: "Hagerstown" },
  { name: "Laurel" },
  { name: "Rockville" },
  { name: "Salisbury" },
],
  "ME": [
  { name: "Auburn" },
  { name: "Augusta" },
  { name: "Bangor" },
  { name: "Biddeford" },
  { name: "Lewiston" },
  { name: "Portland" },
  { name: "Saco" },
  { name: "Sanford" },
  { name: "South Portland" },
],
  "MI": [
  { name: "Ann Arbor" },
  { name: "Dearborn" },
  { name: "Detroit" },
  { name: "Flint" },
  { name: "Grand Rapids" },
  { name: "Kalamazoo" },
  { name: "Lansing" },
  { name: "Sterling Heights" },
  { name: "Traverse City" },
  { name: "Troy" },
  { name: "Warren" },
],
  "MN": [
  { name: "Bloomington" },
  { name: "Brooklyn Park" },
  { name: "Duluth" },
  { name: "Eagan" },
  { name: "Minneapolis" },
  { name: "Plymouth" },
  { name: "Rochester" },
  { name: "St. Cloud" },
  { name: "St. Paul" },
  { name: "Woodbury" },
],
  "MO": [
  { name: "Blue Springs" },
  { name: "Columbia" },
  { name: "Independence" },
  { name: "Kansas City" },
  { name: "Lee's Summit" },
  { name: "O'Fallon" },
  { name: "Springfield" },
  { name: "St. Charles" },
  { name: "St. Joseph" },
  { name: "St. Louis" },
],
  "MS": [
  { name: "Biloxi" },
  { name: "Clinton" },
  { name: "Greenville" },
  { name: "Gulfport" },
  { name: "Hattiesburg" },
  { name: "Jackson" },
  { name: "Meridian" },
  { name: "Olive Branch" },
  { name: "Southaven" },
  { name: "Tupelo" },
],
  "MT": [
  { name: "Anaconda" },
  { name: "Billings" },
  { name: "Bozeman" },
  { name: "Butte" },
  { name: "Great Falls" },
  { name: "Havre" },
  { name: "Helena" },
  { name: "Kalispell" },
  { name: "Missoula" },
],
  "NC": [
  { name: "Asheville" },
  { name: "Cary" },
  { name: "Charlotte" },
  { name: "Concord" },
  { name: "Durham" },
  { name: "Fayetteville" },
  { name: "Greensboro" },
  { name: "High Point" },
  { name: "Raleigh" },
  { name: "Wilmington" },
  { name: "Winston-Salem" },
],
  "ND": [
  { name: "Bismarck" },
  { name: "Dickinson" },
  { name: "Fargo" },
  { name: "Grand Forks" },
  { name: "Mandan" },
  { name: "Minot" },
  { name: "West Fargo" },
  { name: "Williston" },
],
  "NE": [
  { name: "Bellevue" },
  { name: "Fremont" },
  { name: "Grand Island" },
  { name: "Hastings" },
  { name: "Kearney" },
  { name: "Lincoln" },
  { name: "Norfolk" },
  { name: "North Platte" },
  { name: "Omaha" },
],
  "NH": [
  { name: "Concord" },
  { name: "Derry" },
  { name: "Dover" },
  { name: "Londonderry" },
  { name: "Manchester" },
  { name: "Merrimack" },
  { name: "Nashua" },
  { name: "Rochester" },
  { name: "Salem" },
],
  "NJ": [
  { name: "Camden" },
  { name: "Clifton" },
  { name: "Edison" },
  { name: "Elizabeth" },
  { name: "Jersey City" },
  { name: "Lakewood" },
  { name: "Newark" },
  { name: "Paterson" },
  { name: "Toms River" },
  { name: "Trenton" },
  { name: "Woodbridge" },
],
  "NM": [
  { name: "Albuquerque" },
  { name: "Carlsbad" },
  { name: "Clovis" },
  { name: "Farmington" },
  { name: "Hobbs" },
  { name: "Las Cruces" },
  { name: "Rio Rancho" },
  { name: "Roswell" },
  { name: "Santa Fe" },
],
  "NV": [
  { name: "Boulder City" },
  { name: "Carson City" },
  { name: "Elko" },
  { name: "Henderson" },
  { name: "Las Vegas" },
  { name: "Mesquite" },
  { name: "North Las Vegas" },
  { name: "Reno" },
  { name: "Sparks" },
],
  "NY": [
  { name: "Albany" },
  { name: "Buffalo" },
  { name: "Ithaca" },
  { name: "Mount Vernon" },
  { name: "New Rochelle" },
  { name: "New York City" },
  { name: "Rochester" },
  { name: "Schenectady" },
  { name: "Syracuse" },
  { name: "Utica" },
  { name: "White Plains" },
  { name: "Yonkers" },
],
  "OH": [
  { name: "Akron" },
  { name: "Canton" },
  { name: "Cincinnati" },
  { name: "Cleveland" },
  { name: "Columbus" },
  { name: "Dayton" },
  { name: "Lorain" },
  { name: "Parma" },
  { name: "Springfield" },
  { name: "Toledo" },
  { name: "Youngstown" },
],
  "OK": [
  { name: "Broken Arrow" },
  { name: "Edmond" },
  { name: "Enid" },
  { name: "Lawton" },
  { name: "Moore" },
  { name: "Muskogee" },
  { name: "Norman" },
  { name: "Oklahoma City" },
  { name: "Stillwater" },
  { name: "Tulsa" },
],
  "OR": [
  { name: "Beaverton" },
  { name: "Bend" },
  { name: "Corvallis" },
  { name: "Eugene" },
  { name: "Gresham" },
  { name: "Hillsboro" },
  { name: "Medford" },
  { name: "Portland" },
  { name: "Salem" },
  { name: "Springfield" },
],
  "PA": [
  { name: "Allentown" },
  { name: "Bethlehem" },
  { name: "Erie" },
  { name: "Harrisburg" },
  { name: "Lancaster" },
  { name: "Philadelphia" },
  { name: "Pittsburgh" },
  { name: "Reading" },
  { name: "Scranton" },
  { name: "State College" },
  { name: "York" },
],
  "RI": [
  { name: "Central Falls" },
  { name: "Cranston" },
  { name: "East Providence" },
  { name: "Newport" },
  { name: "Pawtucket" },
  { name: "Providence" },
  { name: "Warwick" },
  { name: "Woonsocket" },
],
  "SC": [
  { name: "Charleston" },
  { name: "Columbia" },
  { name: "Florence" },
  { name: "Greenville" },
  { name: "Mount Pleasant" },
  { name: "North Charleston" },
  { name: "Rock Hill" },
  { name: "Spartanburg" },
  { name: "Summerville" },
  { name: "Sumter" },
],
  "SD": [
  { name: "Aberdeen" },
  { name: "Brookings" },
  { name: "Huron" },
  { name: "Mitchell" },
  { name: "Pierre" },
  { name: "Rapid City" },
  { name: "Sioux Falls" },
  { name: "Watertown" },
  { name: "Yankton" },
],
  "TN": [
  { name: "Bartlett" },
  { name: "Chattanooga" },
  { name: "Clarksville" },
  { name: "Franklin" },
  { name: "Jackson" },
  { name: "Johnson City" },
  { name: "Knoxville" },
  { name: "Memphis" },
  { name: "Murfreesboro" },
  { name: "Nashville" },
],
  "TX": [
  { name: "Amarillo" },
  { name: "Arlington" },
  { name: "Austin" },
  { name: "Corpus Christi" },
  { name: "Dallas" },
  { name: "El Paso" },
  { name: "Fort Worth" },
  { name: "Garland" },
  { name: "Houston" },
  { name: "Irving" },
  { name: "Laredo" },
  { name: "Lubbock" },
  { name: "McKinney" },
  { name: "Plano" },
  { name: "San Antonio" },
],
  "UT": [
  { name: "Layton" },
  { name: "Logan" },
  { name: "Ogden" },
  { name: "Orem" },
  { name: "Provo" },
  { name: "Salt Lake City" },
  { name: "Sandy" },
  { name: "St. George" },
  { name: "West Jordan" },
  { name: "West Valley City" },
],
  "VA": [
  { name: "Alexandria" },
  { name: "Chesapeake" },
  { name: "Hampton" },
  { name: "Lynchburg" },
  { name: "Newport News" },
  { name: "Norfolk" },
  { name: "Portsmouth" },
  { name: "Richmond" },
  { name: "Roanoke" },
  { name: "Suffolk" },
  { name: "Virginia Beach" },
],
  "VT": [
  { name: "Barre" },
  { name: "Burlington" },
  { name: "Middlebury" },
  { name: "Montpelier" },
  { name: "Rutland" },
  { name: "South Burlington" },
  { name: "St. Albans" },
  { name: "Winooski" },
],
  "WA": [
  { name: "Bellevue" },
  { name: "Bellingham" },
  { name: "Everett" },
  { name: "Kent" },
  { name: "Olympia" },
  { name: "Renton" },
  { name: "Seattle" },
  { name: "Spokane" },
  { name: "Tacoma" },
  { name: "Vancouver" },
  { name: "Yakima" },
],
  "WI": [
  { name: "Appleton" },
  { name: "Eau Claire" },
  { name: "Green Bay" },
  { name: "Janesville" },
  { name: "Kenosha" },
  { name: "Madison" },
  { name: "Milwaukee" },
  { name: "Oshkosh" },
  { name: "Racine" },
  { name: "Waukesha" },
],
  "WV": [
  { name: "Beckley" },
  { name: "Charleston" },
  { name: "Fairmont" },
  { name: "Huntington" },
  { name: "Martinsburg" },
  { name: "Morgantown" },
  { name: "Parkersburg" },
  { name: "Weirton" },
  { name: "Wheeling" },
],
  "WY": [
  { name: "Casper" },
  { name: "Cheyenne" },
  { name: "Gillette" },
  { name: "Green River" },
  { name: "Jackson" },
  { name: "Laramie" },
  { name: "Riverton" },
  { name: "Rock Springs" },
  { name: "Sheridan" },
],
};

export const isUsCountry = (code: string) => code === "US";

export const getCitiesForCountry = (countryCode: string): CityEntry[] =>
  CITIES_BY_COUNTRY[countryCode.trim().toUpperCase()] ?? [];

export const getUsStates = (): UsStateEntry[] => US_STATES;

export const getCitiesForUsState = (stateCode: string): CityEntry[] =>
  US_CITIES_BY_STATE[stateCode.trim().toUpperCase()] ?? [];

export const filterCityEntries = (entries: CityEntry[], query: string): CityEntry[] => {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return entries;
  return entries.filter((entry) => entry.name.toLowerCase().includes(normalized));
};

export const filterUsStates = (states: UsStateEntry[], query: string): UsStateEntry[] => {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return states;
  return states.filter(
    (state) =>
      state.name.toLowerCase().includes(normalized) || state.code.toLowerCase().includes(normalized),
  );
};

export const formatUsDestinationCity = (cityName: string, stateCode: string): string =>
  `${cityName}, ${stateCode.trim().toUpperCase()}`;