export const API_ENDPOINTS = {
  auth: {
    signIn: "/auth/sign-in",
    signUp: "/auth/sign-up",
    signOut: "/auth/sign-out",
    refresh: "/auth/refresh",
    restoreAccount: "/auth/restore-account",
    restoreAccountRequest: "/auth/restore-account/request",
    restoreAccountVerify: "/auth/restore-account/verify",
    me: "/auth/me",
    verifyPhone: "/auth/verify-phone",
    verifyEmail: "/auth/verify-email",
    resendPhoneCode: "/auth/resend-phone-code",
    resendEmailCode: "/auth/resend-email-code",
    forgotPasswordRequest: "/auth/forgot-password/request",
    forgotPasswordVerify: "/auth/forgot-password/verify",
    changePassword: "/auth/change-password",
  },
  onboarding: {
    complete: "/onboarding/complete",
  },
  explore: {
    feed: "/explore/feed",
  },
  snaps: {
    create: "/snaps",
    me: "/snaps/me",
    byUser: "/users/:userId/snaps",
    delete: "/snaps/:snapId",
    like: "/snaps/:snapId/like",
    comments: "/snaps/:snapId/comments",
    comment: "/snaps/:snapId/comments/:commentId",
    commentLike: "/snaps/:snapId/comments/:commentId/like",
  },
  events: {
    list: "/events",
    detail: "/events/:eventId",
    album: "/events/:eventId/album",
    rating: "/events/:eventId/rating",
    moments: "/events/:eventId/moments",
    toggleAttendance: "/events/:eventId/attendance/toggle",
    create: "/events",
    myAttendances: "/events/my-attendances",
    group: "/events/:eventId/group",
    archiveGroup: "/events/:eventId/group/archive",
    removeGroupMember: "/events/:eventId/group/members/:userId",
  },
  help: {
    list: "/help/requests",
    detail: "/help/requests/:requestId",
    create: "/help/requests",
    respond: "/help/requests/:requestId/respond",
    updateStatus: "/help/requests/:requestId/status",
    delete: "/help/requests/:requestId",
  },
  messages: {
    conversations: "/messages/conversations",
    requests: "/messages/requests",
    conversationDetail: "/messages/conversations/:threadId",
    messages: "/messages/conversations/:threadId/messages",
    sendMessage: "/messages/conversations/:threadId/messages",
    directConversation: "/messages/conversations/direct",
    markRead: "/messages/conversations/:threadId/read",
    acceptConversation: "/messages/conversations/:threadId/accept",
    pinMessage: "/messages/conversations/:threadId/pin",
    unpinMessage: "/messages/conversations/:threadId/pin",
    helpConversation: "/messages/help-conversations",
  },
  profile: {
    updateAvatar: "/profile/avatar",
    deleteAccount: "/profile/delete-account",
  },
  users: {
    search: "/users/search",
    blocked: "/users/blocked",
    block: "/users/:userId/block",
    blockStatus: "/users/:userId/block-status",
    follow: "/users/:userId/follow",
    followStatus: "/users/:userId/follow-status",
    myFollowing: "/users/me/following",
    myFollowers: "/users/me/followers",
    myFriends: "/users/me/friends",
    organizerEvents: "/users/:userId/events",
  },
  complaints: {
    create: "/complaints",
  },
  support: {
    report: "/support/report",
  },
  notifications: {
    list: "/notifications",
    unreadCount: "/notifications/unread-count",
    readAll: "/notifications/read-all",
    markRead: "/notifications/:notificationId/read",
  },
  organizer: {
    apply: "/organizer/apply",
    status: "/organizer/status",
    myEvents: "/organizer/events",
  },
} as const;
